import { EvaluationsClient } from '@/lib/api/evaluations'

// Mock the request method
const mockRequest = jest.fn()

// Create a test instance with mocked request
const createTestClient = () => {
  const client = new EvaluationsClient()
  ;(client as any).request = mockRequest
  return client
}

describe('Upload Data Format Fix', () => {
  beforeEach(() => {
    jest.clearAllMocks()
  })

  it('should correctly detect and upload QA questions', async () => {
    const client = createTestClient()

    // Mock successful response
    mockRequest.mockResolvedValue({
      message: 'Questions added successfully',
      added_count: 2,
      success: true,
    })

    // Create a file with QA questions in the format generated by questionsToJson
    const questionsData = [
      {
        question: 'What is contract law?',
        answer: 'Contract law is the body of law that governs agreements.',
      },
      {
        question: 'What is tort law?',
        answer: 'Tort law deals with civil wrongs.',
      },
    ]

    const file = new File([JSON.stringify(questionsData)], 'questions.json', {
      type: 'application/json',
    })

    // Test the upload
    const result = await client.uploadData(
      file,
      'test-task-id',
      'Test questions'
    )

    // Verify the request was made correctly
    expect(mockRequest).toHaveBeenCalledWith(
      '/tasks/test-task-id/add-questions',
      expect.objectContaining({
        method: 'POST',
        body: JSON.stringify({ questions: questionsData }),
      })
    )

    // Verify the response
    expect(result).toEqual({
      message: 'Questions added successfully',
      data_id: 'test-task-id',
      task_id: 'test-task-id',
      status: 'success',
      uploaded_items: 2,
    })
  })

  it('should reject files with old question_data format', async () => {
    const client = createTestClient()

    // Create a file with the old wrapped format
    const oldFormatData = [
      {
        id: '1',
        question_data: {
          Frage: 'What is contract law?',
          Antwort: 'Contract law is...',
        },
      },
    ]

    const file = new File(
      [JSON.stringify(oldFormatData)],
      'old-questions.json',
      { type: 'application/json' }
    )

    // Test should throw error for unknown content type
    await expect(
      client.uploadData(file, 'test-task-id', 'Test')
    ).rejects.toThrow('Unknown content type')
  })

  it('should correctly detect and upload prompts', async () => {
    const client = createTestClient()

    // Mock successful response
    mockRequest.mockResolvedValue({
      message: 'Prompts added successfully',
      added_count: 1,
      success: true,
    })

    // Create a file with prompts
    const promptsData = [
      {
        prompt: 'Generate a legal analysis',
        expected_output: 'The analysis should include...',
        metadata: {
          temperature: 0.7,
          max_tokens: 1000,
        },
      },
    ]

    const file = new File([JSON.stringify(promptsData)], 'prompts.json', {
      type: 'application/json',
    })

    // Test the upload
    const result = await client.uploadData(file, 'test-task-id', 'Test prompts')

    // Verify correct endpoint was called
    expect(mockRequest).toHaveBeenCalledWith(
      '/tasks/test-task-id/add-prompts',
      expect.objectContaining({
        method: 'POST',
        body: JSON.stringify({ prompts: promptsData }),
      })
    )

    // Verify the response
    expect(result.status).toBe('success')
  })
})
