"""
Unit tests for report_service.py

Tests the progressive report building system including:
- Report creation on project creation
- Section updates (data, annotations, generation, evaluation)
- Publishing validation
- Chart data aggregation with metric metadata
"""

import uuid
from datetime import datetime

import pytest
from sqlalchemy.orm import Session

# Import test fixtures from conftest


class TestReportService:
    """Test suite for report_service.py functions"""

    @pytest.fixture
    def setup_project(self, test_db: Session, test_user):
        """Create a test project for report tests"""
        from project_models import Project

        project = Project(
            id=str(uuid.uuid4()),
            title="Test Report Project",
            description="A project for testing reports",
            created_by=test_user.id,
        )
        test_db.add(project)
        test_db.commit()
        test_db.refresh(project)
        return project

    @pytest.fixture
    def setup_tasks(self, test_db: Session, setup_project):
        """Create test tasks for a project"""
        from project_models import Task

        tasks = []
        for i in range(5):
            task = Task(
                id=str(uuid.uuid4()),
                project_id=setup_project.id,
                inner_id=i + 1,
                data={"question": f"Test question {i}", "answer": f"Test answer {i}"},
            )
            test_db.add(task)
            tasks.append(task)

        test_db.commit()
        return tasks

    @pytest.fixture
    def setup_annotations(self, test_db: Session, setup_project, setup_tasks, test_user):
        """Create test annotations for tasks"""
        from project_models import Annotation

        annotations = []
        for task in setup_tasks[:3]:  # Annotate first 3 tasks
            annotation = Annotation(
                id=str(uuid.uuid4()),
                task_id=task.id,
                project_id=setup_project.id,
                completed_by=test_user.id,
                result={"answer": "annotated answer"},
                was_cancelled=False,
                created_at=datetime.utcnow(),
            )
            test_db.add(annotation)
            annotations.append(annotation)

        test_db.commit()
        return annotations

    @pytest.fixture
    def setup_generations(self, test_db: Session, setup_project, setup_tasks, test_user):
        """Create test generations for tasks"""
        from models import Generation, ResponseGeneration

        # Create parent ResponseGeneration for first model
        response_gen_1 = ResponseGeneration(
            id=str(uuid.uuid4()),
            project_id=setup_project.id,
            model_id="gpt-4",
            status="completed",
            created_by=test_user.id,
        )
        test_db.add(response_gen_1)

        # Create parent ResponseGeneration for second model
        response_gen_2 = ResponseGeneration(
            id=str(uuid.uuid4()),
            project_id=setup_project.id,
            model_id="claude-3-opus",
            status="completed",
            created_by=test_user.id,
        )
        test_db.add(response_gen_2)
        test_db.commit()

        # Create individual generations
        generations = []
        model_to_response_gen = {"gpt-4": response_gen_1, "claude-3-opus": response_gen_2}
        for task in setup_tasks:
            for model in ["gpt-4", "claude-3-opus"]:
                gen = Generation(
                    id=str(uuid.uuid4()),
                    generation_id=model_to_response_gen[model].id,
                    task_id=task.id,
                    model_id=model,
                    case_data=task.data.get("question", "Test question"),
                    response_content=f"Generated by {model}",
                )
                test_db.add(gen)
                generations.append(gen)

        test_db.commit()
        return generations, response_gen_1

    @pytest.fixture
    def setup_evaluations(self, test_db: Session, setup_project, test_user):
        """Create test evaluations for a project"""
        from models import EvaluationRun

        evaluations = []
        for model in ["gpt-4", "claude-3-opus"]:
            evaluation = EvaluationRun(
                id=str(uuid.uuid4()),
                project_id=setup_project.id,
                model_id=model,
                evaluation_type_ids=["exact_match", "f1", "bleu"],
                metrics={
                    "exact_match": 0.85 if model == "gpt-4" else 0.82,
                    "f1": 0.92 if model == "gpt-4" else 0.89,
                    "bleu": 0.78 if model == "gpt-4" else 0.75,
                },
                status="completed",
                created_by=test_user.id,
                created_at=datetime.utcnow(),
                completed_at=datetime.utcnow(),
            )
            test_db.add(evaluation)
            evaluations.append(evaluation)

        test_db.commit()
        return evaluations


class TestCreateInitialReportDraft(TestReportService):
    """Tests for create_initial_report_draft()"""

    def test_creates_report_with_project_info(self, test_db: Session, setup_project, test_user):
        """Test that initial report is created with project info populated"""
        from report_service import create_initial_report_draft

        report = create_initial_report_draft(test_db, setup_project.id, test_user.id)

        assert report is not None
        assert report.project_id == setup_project.id
        assert report.created_by == test_user.id
        assert report.is_published is False

        # Check project_info section is populated
        content = report.content
        assert content["sections"]["project_info"]["status"] == "completed"
        assert "Test Report Project" in content["sections"]["project_info"]["title"]

        # Check other sections are pending
        assert content["sections"]["data"]["status"] == "pending"
        assert content["sections"]["annotations"]["status"] == "pending"
        assert content["sections"]["generation"]["status"] == "pending"
        assert content["sections"]["evaluation"]["status"] == "pending"

        # Check metadata
        assert "project_info" in content["metadata"]["sections_completed"]
        assert content["metadata"]["can_publish"] is False

    def test_raises_error_for_nonexistent_project(self, test_db: Session, test_user):
        """Test that creating report for nonexistent project raises error"""
        from report_service import create_initial_report_draft

        with pytest.raises(ValueError, match="not found"):
            create_initial_report_draft(test_db, "nonexistent-id", test_user.id)


class TestUpdateReportDataSection(TestReportService):
    """Tests for update_report_data_section()"""

    def test_updates_data_section_with_task_count(
        self, test_db: Session, setup_project, setup_tasks, test_user
    ):
        """Test that data section is updated with correct task count"""
        from report_service import create_initial_report_draft, update_report_data_section

        # Create initial report
        create_initial_report_draft(test_db, setup_project.id, test_user.id)

        # Update data section
        report = update_report_data_section(test_db, setup_project.id)

        assert report is not None
        assert report.content["sections"]["data"]["status"] == "completed"
        assert report.content["sections"]["data"]["task_count"] == 5
        assert "data" in report.content["metadata"]["sections_completed"]

    def test_preserves_custom_text(self, test_db: Session, setup_project, setup_tasks, test_user):
        """Test that custom text is preserved during update"""
        from sqlalchemy.orm.attributes import flag_modified

        from report_service import create_initial_report_draft, update_report_data_section

        # Create initial report
        report = create_initial_report_draft(test_db, setup_project.id, test_user.id)

        # Add custom text - must flag as modified for JSONB column
        report.content["sections"]["data"]["custom_text"] = "Custom data description"
        flag_modified(report, "content")
        test_db.commit()

        # Update data section
        updated_report = update_report_data_section(test_db, setup_project.id)

        assert (
            updated_report.content["sections"]["data"]["custom_text"] == "Custom data description"
        )

    def test_returns_none_for_nonexistent_report(self, test_db: Session, setup_project):
        """Test that update returns None if report doesn't exist"""
        from report_service import update_report_data_section

        result = update_report_data_section(test_db, setup_project.id)
        assert result is None


class TestUpdateReportAnnotationsSection(TestReportService):
    """Tests for update_report_annotations_section()"""

    def test_updates_annotations_with_count_and_participants(
        self, test_db: Session, setup_project, setup_tasks, setup_annotations, test_user
    ):
        """Test that annotations section is updated with correct counts and participants"""
        from report_service import create_initial_report_draft, update_report_annotations_section

        # Create initial report
        create_initial_report_draft(test_db, setup_project.id, test_user.id)

        # Update annotations section
        report = update_report_annotations_section(test_db, setup_project.id)

        assert report is not None
        assert report.content["sections"]["annotations"]["status"] == "completed"
        assert report.content["sections"]["annotations"]["annotation_count"] == 3

        # Check participants
        participants = report.content["sections"]["annotations"]["participants"]
        assert len(participants) > 0
        assert any(p["id"] == test_user.id for p in participants)


class TestUpdateReportGenerationSection(TestReportService):
    """Tests for update_report_generation_section()"""

    def test_updates_generation_with_models(
        self, test_db: Session, setup_project, setup_tasks, setup_generations, test_user
    ):
        """Test that generation section is updated with correct models"""
        from report_service import create_initial_report_draft, update_report_generation_section

        # Create initial report
        create_initial_report_draft(test_db, setup_project.id, test_user.id)

        # Update generation section
        report = update_report_generation_section(test_db, setup_project.id)

        assert report is not None
        assert report.content["sections"]["generation"]["status"] == "completed"

        models = report.content["sections"]["generation"]["models"]
        assert "gpt-4" in models
        assert "claude-3-opus" in models

    def test_filters_by_project_id(
        self, test_db: Session, setup_project, setup_tasks, setup_generations, test_user
    ):
        """Test that generation section only includes models from the correct project"""
        from models import Generation, ResponseGeneration
        from project_models import Project
        from report_service import create_initial_report_draft, update_report_generation_section

        # Create another project with different generations
        other_project = Project(
            id=str(uuid.uuid4()),
            title="Other Project",
            description="Another project",
            created_by=test_user.id,
        )
        test_db.add(other_project)

        other_response_gen = ResponseGeneration(
            id=str(uuid.uuid4()),
            project_id=other_project.id,
            model_id="other-model",
            status="completed",
            created_by=test_user.id,
        )
        test_db.add(other_response_gen)
        test_db.commit()

        other_gen = Generation(
            id=str(uuid.uuid4()),
            generation_id=other_response_gen.id,
            task_id=str(uuid.uuid4()),
            model_id="other-model",
            case_data="Other input",
            response_content="Other model output",
        )
        test_db.add(other_gen)
        test_db.commit()

        # Create initial report for original project
        create_initial_report_draft(test_db, setup_project.id, test_user.id)

        # Update generation section
        report = update_report_generation_section(test_db, setup_project.id)

        # Should NOT include other-model
        models = report.content["sections"]["generation"]["models"]
        assert "other-model" not in models
        assert "gpt-4" in models


class TestUpdateReportEvaluationSection(TestReportService):
    """Tests for update_report_evaluation_section()"""

    def test_updates_evaluation_with_metrics(
        self, test_db: Session, setup_project, setup_evaluations, test_user
    ):
        """Test that evaluation section is updated with correct metrics"""
        from report_service import create_initial_report_draft, update_report_evaluation_section

        # Create initial report
        create_initial_report_draft(test_db, setup_project.id, test_user.id)

        # Update evaluation section
        report = update_report_evaluation_section(test_db, setup_project.id)

        assert report is not None
        assert report.content["sections"]["evaluation"]["status"] == "completed"

        # Check methods
        methods = report.content["sections"]["evaluation"]["methods"]
        assert "exact_match" in methods
        assert "f1" in methods
        assert "bleu" in methods

        # Check metrics by model
        metrics = report.content["sections"]["evaluation"]["metrics"]
        assert "gpt-4" in metrics
        assert "claude-3-opus" in metrics
        assert metrics["gpt-4"]["exact_match"] == 0.85


class TestCanPublishReport(TestReportService):
    """Tests for can_publish_report()"""

    def test_cannot_publish_without_tasks(self, test_db: Session, setup_project, test_user):
        """Test that report cannot be published without tasks"""
        from report_service import can_publish_report, create_initial_report_draft

        create_initial_report_draft(test_db, setup_project.id, test_user.id)

        can_publish, reason = can_publish_report(test_db, setup_project.id)

        assert can_publish is False
        assert "tasks" in reason.lower()

    def test_cannot_publish_without_generations(
        self, test_db: Session, setup_project, setup_tasks, test_user
    ):
        """Test that report cannot be published without generations"""
        from report_service import can_publish_report, create_initial_report_draft

        create_initial_report_draft(test_db, setup_project.id, test_user.id)

        can_publish, reason = can_publish_report(test_db, setup_project.id)

        assert can_publish is False
        assert "generation" in reason.lower()

    def test_cannot_publish_without_evaluations(
        self, test_db: Session, setup_project, setup_tasks, setup_generations, test_user
    ):
        """Test that report cannot be published without evaluations"""
        from report_service import can_publish_report, create_initial_report_draft

        create_initial_report_draft(test_db, setup_project.id, test_user.id)

        can_publish, reason = can_publish_report(test_db, setup_project.id)

        assert can_publish is False
        assert "evaluation" in reason.lower()

    def test_can_publish_with_all_requirements(
        self,
        test_db: Session,
        setup_project,
        setup_tasks,
        setup_generations,
        setup_evaluations,
        test_user,
    ):
        """Test that report can be published when all requirements are met"""
        from report_service import can_publish_report, create_initial_report_draft

        create_initial_report_draft(test_db, setup_project.id, test_user.id)

        can_publish, reason = can_publish_report(test_db, setup_project.id)

        assert can_publish is True
        assert "all requirements met" in reason.lower()


class TestGetEvaluationChartsData(TestReportService):
    """Tests for get_evaluation_charts_data()"""

    def test_returns_charts_by_model_and_method(
        self, test_db: Session, setup_project, setup_evaluations, test_evaluation_types
    ):
        """Test that chart data is organized by model and method"""
        from report_service import get_evaluation_charts_data

        chart_data = get_evaluation_charts_data(test_db, setup_project.id)

        # Check by_model structure
        assert "by_model" in chart_data
        assert "gpt-4" in chart_data["by_model"]
        assert "claude-3-opus" in chart_data["by_model"]
        assert chart_data["by_model"]["gpt-4"]["exact_match"] == 0.85

        # Check by_method structure
        assert "by_method" in chart_data
        assert "exact_match" in chart_data["by_method"]
        assert chart_data["by_method"]["exact_match"]["gpt-4"] == 0.85

    def test_includes_metric_metadata(
        self, test_db: Session, setup_project, setup_evaluations, test_evaluation_types
    ):
        """Test that chart data includes metric metadata"""
        from report_service import get_evaluation_charts_data

        chart_data = get_evaluation_charts_data(test_db, setup_project.id)

        assert "metric_metadata" in chart_data
        metadata = chart_data["metric_metadata"]

        # Check that metadata is populated for metrics found
        for metric_name in ["exact_match", "f1", "bleu"]:
            assert metric_name in metadata
            assert "higher_is_better" in metadata[metric_name]
            assert "range" in metadata[metric_name]
            assert "name" in metadata[metric_name]

    def test_llm_judge_metrics_get_correct_scale(self, test_db: Session, setup_project, test_user):
        """Test that LLM Judge metrics get 1-5 scale in metadata"""
        from models import EvaluationRun
        from report_service import get_evaluation_charts_data

        # Create evaluation with LLM Judge metrics
        llm_eval = EvaluationRun(
            id=str(uuid.uuid4()),
            project_id=setup_project.id,
            model_id="gpt-4",
            evaluation_type_ids=["llm_judge_helpfulness", "llm_judge_correctness"],
            metrics={
                "llm_judge_helpfulness": 4.2,
                "llm_judge_correctness": 3.8,
                "llm_judge_pairwise": 0.65,
            },
            status="completed",
            created_by=test_user.id,
        )
        test_db.add(llm_eval)
        test_db.commit()

        chart_data = get_evaluation_charts_data(test_db, setup_project.id)

        metadata = chart_data["metric_metadata"]

        # LLM Judge metrics should have 1-5 scale
        assert metadata["llm_judge_helpfulness"]["range"] == [1, 5]
        assert metadata["llm_judge_correctness"]["range"] == [1, 5]

        # Pairwise should have 0-1 scale
        assert metadata["llm_judge_pairwise"]["range"] == [0, 1]

    def test_returns_empty_for_no_evaluations(self, test_db: Session, setup_project):
        """Test that empty data is returned when no evaluations exist"""
        from report_service import get_evaluation_charts_data

        chart_data = get_evaluation_charts_data(test_db, setup_project.id)

        assert chart_data["by_model"] == {}
        assert chart_data["by_method"] == {}
        assert chart_data["metric_metadata"] == {}


class TestGetReportStatistics(TestReportService):
    """Tests for get_report_statistics()"""

    def test_returns_correct_counts(
        self,
        test_db: Session,
        setup_project,
        setup_tasks,
        setup_annotations,
        setup_generations,
    ):
        """Test that statistics return correct counts"""
        from report_service import get_report_statistics

        stats = get_report_statistics(test_db, setup_project.id)

        assert stats["task_count"] == 5
        assert stats["annotation_count"] == 3
        assert stats["participant_count"] == 1  # Only one user annotated
        assert stats["model_count"] == 2  # gpt-4 and claude-3-opus


class TestGetReportModels(TestReportService):
    """Tests for get_report_models()"""

    def test_returns_unique_models(
        self, test_db: Session, setup_project, setup_tasks, setup_generations
    ):
        """Test that unique models are returned"""
        from report_service import get_report_models

        models = get_report_models(test_db, setup_project.id)

        assert len(models) == 2
        assert "gpt-4" in models
        assert "claude-3-opus" in models


class TestCreateOrUpdateReportFromExistingData(TestReportService):
    """Tests for create_or_update_report_from_existing_data()"""

    def test_creates_report_with_all_existing_data(
        self,
        test_db: Session,
        setup_project,
        setup_tasks,
        setup_annotations,
        setup_generations,
        setup_evaluations,
        test_user,
    ):
        """Test that report is created with all existing project data"""
        from report_service import create_or_update_report_from_existing_data

        report = create_or_update_report_from_existing_data(test_db, setup_project.id, test_user.id)

        assert report is not None

        # All sections should be completed
        assert report.content["sections"]["project_info"]["status"] == "completed"
        assert report.content["sections"]["data"]["status"] == "completed"
        assert report.content["sections"]["annotations"]["status"] == "completed"
        assert report.content["sections"]["generation"]["status"] == "completed"
        assert report.content["sections"]["evaluation"]["status"] == "completed"

        # Check data
        assert report.content["sections"]["data"]["task_count"] == 5
        assert report.content["sections"]["annotations"]["annotation_count"] == 3
        assert len(report.content["sections"]["generation"]["models"]) == 2

    def test_updates_existing_report(self, test_db: Session, setup_project, setup_tasks, test_user):
        """Test that existing report is updated rather than creating a new one"""
        from report_service import (
            create_initial_report_draft,
            create_or_update_report_from_existing_data,
        )

        # Create initial report
        initial_report = create_initial_report_draft(test_db, setup_project.id, test_user.id)
        initial_id = initial_report.id

        # Update with existing data
        updated_report = create_or_update_report_from_existing_data(
            test_db, setup_project.id, test_user.id
        )

        # Should be the same report
        assert updated_report.id == initial_id
        # But with updated content
        assert updated_report.content["sections"]["data"]["status"] == "completed"
