apiVersion: v2
name: benger
description: A Helm chart for BenGER - Benchmark für Deutsches Recht
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: TUM Legal Tech Team
    email: sebastian.nagl@tum.de
dependencies:
  - name: postgresql
    version: "~12.5.3"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "~17.11.3"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled 