\documentclass[11pt]{article}

\usepackage{acl}

\usepackage{latexsym}
\usepackage{iftex}
\ifpdftex
  \usepackage{times}
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp}
  \DeclareUnicodeCharacter{2248}{\ensuremath{\approx}}
  \DeclareUnicodeCharacter{2264}{\ensuremath{\leq}}
  \DeclareUnicodeCharacter{2265}{\ensuremath{\geq}}
\else
  \usepackage{fontspec}
  % Main font: TeX Gyre Termes, bundled under fonts/ and loaded by explicit
  % filename + Path. This keeps the build self-contained on arXiv (no
  % reliance on the TeX Live font-name database or fontconfig, neither of
  % which arXiv's source scanner can see) and lets that scanner find the
  % real files in the upload. TeXGyreTermes-Reg is on aclpubcheck's accepted
  % main-font set and carries the Greek text glyphs (ρ κ σ). Sans/mono are
  % intentionally left at the NFSS defaults — this manuscript embeds no
  % TeX Gyre Heros/Cursor glyphs, so declaring them only tripped arXiv's
  % missing-file scan for fonts the output never used.
  \setmainfont{texgyretermes-regular.otf}[Path=fonts/,
    BoldFont=texgyretermes-bold.otf,
    ItalicFont=texgyretermes-italic.otf,
    BoldItalicFont=texgyretermes-bolditalic.otf]
\fi
\usepackage{microtype}
\usepackage{inconsolata}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{booktabs}
\usepackage{amsmath}
\usepackage{longtable}
\usepackage{fvextra}
\usepackage{multicol}
\usepackage{tcolorbox}
\tcbuselibrary{skins,breakable}

% Prompt environment for German prompt blocks in the appendix.
% breaklines wraps overlong lines so they fit in the column;
% breakanywhere lets the break fall mid-word when no space is reachable.
% breaksymbolleft/right are emptied so wrapped lines don't show the
% default \hookrightarrow marker (the prompts are documentary, not code).
\DefineVerbatimEnvironment{Prompt}{Verbatim}{%
  breaklines=true,breakanywhere=true,fontsize=\footnotesize,%
  breaksymbolleft={},breaksymbolright={},%
  formatcom=\rmfamily}

% Bordered, breakable container for prompts. The J/K/L appendix sections
% are wrapped in \onecolumn so each PromptBox spans the full text width;
% breakable lets long prompts (K.1) flow across pages cleanly. Padding is
% kept tight so the long prompts stay close to a single page.
\newtcolorbox{PromptBox}{%
  enhanced jigsaw, breakable,
  colback=white, colframe=black!50,
  boxrule=0.4pt, arc=1.5pt,
  left=3pt, right=3pt, top=2pt, bottom=2pt,
  before skip=4pt, after skip=4pt}

% Pandoc tight list support
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

% Pandoc bounded image support (Quarto 1.9+)
\providecommand{\pandocbounded}[1]{#1}


\usepackage{afterpage}
\usepackage{colortbl}  % adds \cellcolor / \rowcolor for table highlights
\usepackage{fontspec}
% Text main font stays TeX Gyre Termes (set portably in the ACL
% template's \else branch). aclpubcheck accepts `TeXGyreTermes-Reg`,
% and the font carries the Greek text glyphs (ρ κ σ) used in the
% stats prose, so no STIXGeneral system-font override is needed —
% STIXGeneral is macOS-only and absent from TeX Live, which
% would break the build on arXiv.
\usepackage{unicode-math}
% STIX Two Math bundled under fonts/ and loaded by explicit filename +
% Path so the build is self-contained on arXiv (no reliance on the TeX
% Live font database, which arXiv's source scanner can't see) and the
% scanner finds the real file in the upload.
\setmathfont{STIXTwoMath-Regular.otf}[Path=fonts/]
% Wrap \maketitle in `NoHyper` so the byline `\thanks` symbols
% aren't typeset as hyperlinks. acl.sty resets the footnote
% counter after the title page, which causes hyperref's auto-named
% anchors `Hfootnote.N` to collide between title-page \thanks
% and body \footnote calls. PDF readers then jump from the byline
% symbols (*, †, ‡) to wherever the last colliding anchor lives
% (often deep in the appendix). Suppressing the link annotations
% is the cleanest fix; the footnote *text* still renders at the
% bottom of the title page, exactly as ACL papers conventionally
% typeset it, and the standard reader convention is to look down
% the page for matching symbols.
\makeatletter
\AtBeginDocument{%
  \let\acl@orig@maketitle\maketitle
  \def\maketitle{\begin{NoHyper}\acl@orig@maketitle\end{NoHyper}}%
}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\title{BenGER: Benchmarking LLM Systems on Subsumption-Based Legal
Reasoning in German Law}

\author{
  Sebastian Nagl\textsuperscript{1}\thanks{\,Core Contributor, corresponding author. Correspondence to \texttt{sebastian.nagl@tum.de}.} \quad
  Ann-Kristin Mayrhofer\textsuperscript{2\textdaggerdbl} \quad
  Martin Heidebach\textsuperscript{2\textdaggerdbl} \\
  \bfseries Aleyna Koçak\textsuperscript{3\textdaggerdbl} \quad
  Anne Zettelmeier\textsuperscript{4\textdaggerdbl} \quad
  Elly Breu\textsuperscript{1\textdaggerdbl} \\
  \bfseries Angelina Greiner\textsuperscript{1\textdaggerdbl} \quad
  Sofija Milijas\textsuperscript{1\textdaggerdbl} \quad
  Matthias Grabmair\textsuperscript{1}\thanks{\,Senior author.} \\[6pt]
  \mdseries \textsuperscript{1}Technical University of Munich (TUM) \quad
  \textsuperscript{2}Ludwig Maximilian University of Munich (LMU) \\
  \textsuperscript{3}University of Konstanz \quad
  \textsuperscript{4}University of Saarbrücken\thanks{\,Dataset contributor.}
}

\begin{document}
\maketitle


\begin{abstract}

We introduce the BenGER (Benchmark for German Law) dataset for
evaluating LLM systems on subsumption-based legal reasoning in German
law. The dataset combines 596 exam-style free-text legal case tasks
across multiple levels of legal education with 531 short doctrinal
reasoning tasks, and includes a controlled validation subset of timed
human-written solutions under both unaided and human--AI co-creation
conditions. We evaluate 12 contemporary LLM systems - closed flagship,
efficiency-oriented, and open-weight - with a rubric-aligned
LLM-as-a-Judge cross-validated against a multi-rater human-grading layer
(three blind reviews per solution, six judge families benchmarked
against the human pool). Closed-flagship systems lead the leaderboard
across all three corpora, human--AI co-creation measurably improves on
unaided human work, and the LLM judge tracks human grading at Pearson
r=0.76 and Cohen's κ=0.60, with system rankings stable across judge
families and two judges from independent providers clearing the Calderon
single-reviewer replacement bar on human-authored solutions.

\end{abstract}

\afterpage{%
\begin{figure*}[t!]
\centering
\includegraphics[width=\textwidth]{assets/fig-overview.png}
\caption{Overview of the benchmark and evaluation pipeline. Three German-law corpora -- the published ZJS exam corpus, the short Doctrinal Principles question set, and the controlled Benchathon validation subset with human solutions in two working conditions -- are answered by a panel of LLM systems and scored by a rubric-aligned LLM judge. The Benchathon subset is additionally graded by a blind human reviewer pool (with one author-informed creator review per solution); the resulting human distribution is used to validate the LLM judge.}
\label{fig-overview}
\end{figure*}%
}

\section{Introduction}\label{introduction}

Evaluating legal reasoning is hard. Grading of legal exam answers
exhibits substantial variability even among human experts: Hufeld
\citep{hufeld2024} shows that identical answers in German law exams
receive markedly different scores depending on the grader, reflecting
the interpretive nature of doctrinal legal analysis. This poses a
challenge for recent work on large language models (LLMs): if human
evaluation itself is noisy, what does it mean to benchmark legal
reasoning performance?

Existing benchmarks for legal NLP have evolved rapidly from
classification \citep{chalkidis2022lexglue, guha2023legalbench} to
reasoning capabilities
\citep{fei2024lawbench, fan2026lexam, jia2025readyjuristone, shi2026plawbench}
and retrieval-augmented evaluation
\citep{pipitone2024legalbenchrag, butler2026legalragbench}, but most
emphasise short-form QA, common-law jurisdictions, or stable
ground-truth labels - leaving open-ended subsumption-based German legal
reasoning under noisy expert judgements under-served.

We address these gaps with a benchmark centered on subsumption-based
legal reasoning, the core reasoning paradigm in German law
(Section~\ref{sec-legal-methodology}).

We present the BenGER (Benchmark for German Law) dataset\footnote{Full
  code and dataset are available at
  \url{https://github.com/SebastianNagl/benger-platform}.} for
evaluating LLMs on subsumption-based legal reasoning in German law. The
BenGER dataset consists of three components covering 596 exam-style
free-text legal case tasks across different stages of legal education
and 531 short doctrinal reasoning tasks, and incorporates human
baselines for traditional legal work and human--AI co-creation on a
controlled Benchathon validation subset. Figure~\ref{fig-overview}
summarises the three components and the LLM-generation-plus-evaluation
pipeline. Generation, annotation, and evaluation were run end-to-end on
the BenGER platform \citep{nagl2026benger}, the open-source web
application we previously developed for benchmarking legal-domain LLM
systems.

To evaluate free-text legal reasoning under noisy human judgements, we
adopt a hybrid framework: an LLM-as-a-Judge aligned with German grading
rubrics, cross-validated against three blind human reviews per solution
and an author-informed creator review as a reference signal. We treat
evaluation as a distribution over plausible expert assessments rather
than a single deterministic label.

Our contributions are threefold: (i) we introduce a benchmark for
subsumption-based legal reasoning in German law, (ii) we provide an
empirical evaluation of 12 contemporary LLM systems - closed flagship,
efficiency-oriented, and open-weight - alongside human and co-creative
baselines, and (iii) an evaluation methodology that accounts for the
inherent variability of legal grading.

We organise the empirical analysis of the full BenGER dataset around
five questions. \textbf{RQ1 (Performance):} how well do contemporary LLM
systems solve open-ended subsumption-based German legal reasoning tasks,
and how do they compare to human baselines? \textbf{RQ2 (System-tier
effects):} how does performance vary across system tiers and
open-/closed-weight access modes? \textbf{RQ3 (Evaluation validity):}
how well do generic automatic metrics correlate with rubric-based legal
evaluation? \textbf{RQ4 (Human--AI co-creation):} does AI-assisted
drafting improve human performance, and how does it compare to
standalone LLM systems? \textbf{RQ5 (Grading reliability):} how closely
do LLM-judge evaluations align with the empirical distribution of human
grades, and are their deviations comparable to inter-rater variability?

\section{Subsumption-based legal reasoning}\label{sec-legal-methodology}

Subsumption-based legal reasoning is the core reasoning paradigm of
German civil-law doctrine
\citep{larenz1995methodenlehre, moellers2023methodenlehre}. Unlike
common-law systems, where reasoning proceeds primarily through analogy
to precedent, German legal analysis derives outcomes from codified
statutory norms via a structured four-step scaffold - \emph{Obersatz}
(the legal claim or norm hypothesis to be examined), \emph{Definition}
(interpretation of the norm's elements), \emph{Subsumtion} (anchoring of
the concrete facts under those elements), and \emph{Ergebnis} (the
resulting legal consequence). This \emph{Gutachtenstil} register
(opinion style, where the conclusion follows the reasoning) - distinct
from the result-first \emph{Urteilsstil} (judgement style) used in
judicial decisions - is the form in which German legal education, state
examinations, and entry-level legal practice are trained and assessed;
grading targets the written \emph{Falllösung} end-to-end rather than the
final answer alone, because the rubric rewards how each norm element is
anchored in the specific fact pattern. This makes subsumption-based
reasoning a structurally demanding generation task: a system has to
identify the governing norm, articulate its elements, anchor every
element in the facts, and conclude - a chain in which surface fluency
can mask a missing \emph{Subsumtion} step. It also makes the task
unusually amenable to rubric-based evaluation, because each step in the
scaffold maps to an identifiable component of the generated answer
rather than to a global quality impression. The English-language legal
NLP benchmarks centered on classification, multiple-choice, or
precedent-style reasoning
\citep{chalkidis2022lexglue, guha2023legalbench} do not exercise this
scaffold, leaving German subsumption-based legal reasoning under noisy
expert judgement under-served.

\section{Related work}\label{related-work}

Legal NLP benchmarking has evolved from classification baselines -
LexGLUE \citep{chalkidis2022lexglue} (seven English legal datasets) and
LegalBench \citep{guha2023legalbench} (162 mostly short-form
US-federal-law tasks) - to reasoning-centric, jurisdiction-specific
evaluation. Recent work targets jurisdiction-specific reasoning:
LawBench \citep{fei2024lawbench} and LexEval \citep{li2024lexeval} for
Chinese civil law, KBL \citep{kim2024kbl} for Korean bar-exam questions,
LAR-ECHR \citep{chlapanis2024larechr} for European Court of Human Rights
argument chains, KOBLEX \citep{lee2025koblex} for provision-grounded
multi-hop reasoning in Korean law, GreekBarBench
\citep{chlapanis2025greekbarbench} for free-text Greek bar exams,
NitiBench \citep{akarajaradwong2025nitibench} for Thai financial and tax
law, PLawBench \citep{shi2026plawbench} for rubric-graded Chinese legal
practice across 13 practical scenarios, and LaborBench
\citep{hariri2025laborbench} for US state labor-law statutory
simplification. A complementary line targets retrieval-augmented
evaluation - LegalBench-RAG \citep{pipitone2024legalbenchrag} and Legal
RAG Bench \citep{butler2026legalragbench} - and discrepancy-based
auditing of LLM legal reasoning - CLAUSE \citep{choudhury2026clause}.
The closest precedent is LEXam \citep{fan2026lexam} - 7,537 questions
across 340 law exams in English and German, with an ensemble
LLM-as-a-Judge validated against human experts - but its rubric is not
the \emph{Obersatz--Definition--Subsumtion--Ergebnis} scaffold central
to German \emph{Falllösung} grading
(Section~\ref{sec-legal-methodology}) and it does not couple its
free-text items to the dimension-level grading criteria used in German
law school and state-exam evaluation.

Evaluating free-text legal reasoning relies increasingly on
LLM-as-a-Judge approaches, which raises concerns over bias, calibration,
and alignment with expert judgement. Research in German legal education
shows that human grading itself is substantially variable: Hufeld
\citep{hufeld2024} reports an experiment with 15 beginner-level law
exams and 23 graders, in which the same submissions received 15 or 16
independent grades each - the average range between the lowest and
highest grade per answer was 6.47 points on the German 0--18 scale, and
only 42\% of grades fell within ±1 point of the answer-specific mean.
Evaluation in legal reasoning tasks is therefore better treated as a
distribution over plausible expert judgements than as a single ground
truth, motivating hybrid methodologies that combine human expertise with
calibrated LLM-based scoring.

Resources for German legal NLP remain limited: GerLayQA
\citep{buttner2024gerlayqa} provides \textasciitilde21,000 lay questions
paired with lawyer answers but focuses on QA rather than
subsumption-based reasoning, GerLeRB \citep{weber2025gerlerb} targets
legislative retrieval, and our prior BenGER platform
\citep{nagl2026benger} provides an end-to-end framework for German legal
case analysis and subsumption-based reasoning workflows on which the
present dataset was built. German legal reasoning grounded in doctrinal
subsumption under statutory law remains under-served, especially for
open-ended, structured analysis under noisy human judgements. The BenGER
dataset addresses this gap by combining a 596-task exam-style corpus and
531 short doctrinal reasoning items with a controlled Benchathon
validation subset, a German doctrinal rubric, and a multi-rater
cross-validation protocol.

\section{Dataset}\label{dataset}

The BenGER dataset draws on three components covering the main forms of
legal reasoning in German legal education: two exam-style case corpora
in which a fact pattern is given and a structured \emph{Falllösung} is
expected, and one set of short doctrinal reasoning items that probes
core principles without the full case-analysis scaffolding.

The ZJS corpus contributes 581 publicly available exam-style cases from
the \emph{Zeitschrift für das Juristische Studium} (Journal of Legal
Studies)\footnote{\url{https://www.zjs-online.com/}}, covering civil,
criminal, and public law and spanning early undergraduate exercises
through first and selected second state-examination materials, each
paired with an expert-written reference solution. The Benchathon corpus
adds 15 newly collected exam-style tasks at an intermediate difficulty
level (more demanding than introductory exercises, less complex than
full first-state-exam problems), each with 220 human solutions (65
traditional, 155 human--AI co-creation).\footnote{The corpus is named
  after the in-person Benchathon event at which participants produced
  these solutions and the validation human grading. Participants were
  predominantly law students at various stages of legal training, plus a
  smaller group of \emph{Referendare} (post-state-exam legal trainees),
  recent graduates, and a small layperson cohort; full composition in
  Appendix \ref{benchathon-participant-composition}.} The Doctrinal
Principles corpus (\emph{Grundprinzipien}) contributes 531 short
doctrinal reasoning items (question--answer pairs with explanatory
reasoning) on core principles, with recent case law where appropriate.
ZJS supports at-scale automated evaluation; Benchathon supports the
human baseline + judge-validation layer; Doctrinal Principles probes the
same reasoning at shorter form.

The benchmark is intended for evaluation only; we do not define a
train/test split, since the objective is comparative evaluation of
deployed LLM systems and human baselines. Pretraining-contamination
considerations across the three corpora are discussed in §Limitations.

\subsection{Benchathon task design and human solution
collection}\label{benchathon-task-design-and-human-solution-collection}

Benchathon participants solved tasks in a controlled annotation
environment, with each task randomly assigned to one of two conditions:
in the \emph{traditional} condition, participants could use statutory
texts, legal databases, literature, and internet research; in the
\emph{co-creation} condition, participants were additionally free to use
any LLM(s) of their choosing - commercial or open-weight, in any
combination - through their own accounts; we did not log which tool a
given participant used. The co-creation arm therefore measures an upper
bound on what human--LLM teams currently achieve with off-the-shelf
assistance, not a controlled comparison against any specific system.
Only the final written solution is evaluated, mirroring legal
examination practice; auxiliary materials (notes, outlines, span
markings) were retained for future analysis but are not used here
(Appendix \ref{full-benchathon-human-evaluation-assignment-procedure}).
Each task had a two-hour time limit; participant expertise was measured
objectively (reported legal grades and qualifications) and subjectively
(self-assessed competence on a Likert scale).

\section{Experimental setup}\label{experimental-setup}

\subsection{Generation}\label{generation}

We evaluate 12 contemporary LLM systems through Cloud-APIs. Per-system
providers, snapshots, observed temperatures, token-budget settings,
truncation counts, and the short aliases used in the body are in
Table~\ref{tbl-system-overview} (Appendix C). Each task received at
least one generation per system; flagship and large-context systems
received additional repetitions where capacity allowed. The Benchathon
subset was generated by all systems; on ZJS, all 12 systems produced
coverage of up to 581 published exams.\footnote{Individual questions
  were occasionally flagged as prohibited content by the provider's
  safety filter, leaving a small handful of per-system coverage gaps
  below the corpus total.}

All systems were prompted with the same German-language system and
instruction prompts (Appendix \ref{system-prompts-for-generation} +
\ref{instruction-prompts-for-generation}) and configured to return a
single JSON object containing the full case solution
(\emph{Falllösung}), with the instruction prompt mirroring the
\emph{Gutachtenstil} scaffold (Section~\ref{sec-legal-methodology}).
Provider-recommended temperatures and token budgets were used
(temperature 0.0--1.0, max output 8,000--16,000 tokens); generations
malformed or shorter than 200 output tokens after a bounded retry budget
were excluded. Truncation in kept generations is concentrated in the
smaller open-weight systems (Table~\ref{tbl-system-overview}).

\subsection{Black-box system
evaluation}\label{black-box-system-evaluation}

We evaluate LLM systems through provider APIs in a black-box setting, so
our results measure end-to-end system behaviour rather than isolated
base-model capability. We do not enable retrieval or tool-use endpoints;
components we cannot disable - notably content filters and, on some
products, internal routing between sub-models - operate by default. This
reflects realistic deployment conditions but limits causal claims about
underlying architectures.

\subsection{Automatic metrics}\label{automatic-metrics}

Per generation we compute BLEU \citep{papineni2002bleu}, ROUGE
\citep{lin2004rouge}, METEOR \citep{banerjee2005meteor}, chrF, BERTScore
\citep{zhang2020bertscore}, MoverScore \citep{zhao2019moverscore}, and a
Sentence-BERT cosine similarity \citep{reimers2019sentencebert} against
the expert reference solution. Per-system means appear in the main
leaderboard tables; per-generation values are correlated against the
LLM-judge rubric score in RQ3.

\subsection{LLM-as-a-Judge evaluation}\label{llm-as-a-judge-evaluation}

For rubric-based automatic evaluation, we use a specialized
LLM-as-a-Judge prompt aligned with German legal grading practices. The
judge receives the task, the reference solution, and the solution to be
evaluated. It assigns scores across ten dimensions covering result
correctness (\emph{Ergebnisrichtigkeit}), issue identification
(\emph{Vollständigkeit}), legal grounding (\emph{Rechtsgrundlagen}),
doctrinal knowledge (\emph{Rechtskenntnis}), subsumption quality
(\emph{Subsumtion}), problem depth (\emph{Schwerpunktsetzung}),
methodological structure (\emph{Methodischer Stil}), organization
(\emph{Gliederung}), terminology (\emph{Sprache}), and formal
correctness (\emph{Formalia}). Dimension scores are aggregated to a
100-point raw score and mapped to the German 0--18 grade-point scale. A
generation counts as a \emph{pass} when its grade-point score reaches
\emph{ausreichend} (≥ 4 on the 0--18 scale, corresponding to a raw score
of ≥ 50/100), following the German \emph{Staatsexamen} (state law
examination) convention; this is the boolean reported in the \emph{Pass}
columns of Table~\ref{tbl-main-leaderboard} and in the pass-rate
aggregates throughout. The rubric operationalises the
\emph{Gutachtenstil} scaffold (Section~\ref{sec-legal-methodology}):
each step in the \emph{Obersatz--Definition--Subsumtion--Ergebnis}
schema is reflected in a dedicated dimension (issue identification,
legal grounding, doctrinal knowledge, subsumption quality,
methodological structure), so the per-dimension scores in
Figure~\ref{fig-rubric-dim} correspond to identifiable components of the
reasoning process.

The judge is blind to solution origin and receives inputs in a fixed
(task, reference, candidate) order. The primary judge is GPT-5.4-mini;
configuration in Appendix \ref{llm-judge-configuration}, prompt in
Appendix \ref{evaluation-prompts-for-the-llm-judge}. Since judge-based
evaluation may itself be model-dependent, we cross-validate the judge
against a multi-rater human-grading layer on a Benchathon subset (design
below; results in RQ5). To quantify judge stability we additionally run
two complementary checks on the Benchathon subset - \emph{within-judge
stochasticity} (k=3 re-runs of GPT-5.4-mini) and \emph{between-judge
bias} (additional evaluations by Opus-4.7, Gemini-3.1-Pro,
DeepSeek-V4-Pro, Qwen3.5-397B-A17B, and Sonnet-4.6); both are reported
in RQ5. Outputs conform to a predefined JSON schema; non-conforming
outputs are retried and reported as evaluation failures if they cannot
be parsed.

\subsection{Human evaluation}\label{sec-human-eval}

Human evaluation is conducted on a controlled subset of 45 Benchathon
solutions: one traditional human, one human--AI co-created, and one
LLM-generated solution per Benchathon task. Human submissions are
selected as the median-expertise participant per legal area
(\emph{Bereich}); LLM submissions are drawn through a tier-balanced
rotation across closed-flagship, efficiency-oriented, and open-weight
reference systems. Each selected solution receives three independent
blind reviews and one author-informed creator review (180 reviews
total). Reviewers grade against the same rubric as the LLM judge and
form the IRR pool used to validate the judge; creator reviews are
excluded from IRR since task authors have privileged knowledge. The
selection procedure, the seven-grader roster, and the \(m=5\) blind
subset are described in
Appendix~\ref{full-benchathon-human-evaluation-assignment-procedure}. We
report descriptive agreement statistics - Spearman, Pearson, MAE,
Cohen's \(\kappa\) \citep{cohen1960coefficient}, ICC(2,1) and ICC(2,k)
\citep{shrout1979intraclass, koo2016guideline} - alongside the Calderon
alt-test \citep{calderon2025} in RQ5. For the alt-test we follow the
blind-pool procedure at \(\varepsilon=0.15\) (Calderon's
skilled-annotator tier) with Benjamini-Yekutieli FDR at \(q=0.05\)
across the \(m\) blind reviewers, and report the single-expert variant
against the un-blind creator grade at \(\varepsilon=0.20\) (with
\(\varepsilon=0.15\) as a sensitivity check); the judge passes when the
winning rate \(\omega \geq 0.5\). The primary judge is GPT-5.4-mini; we
additionally re-score the same picks with Opus-4.7, Gemini-3.1-Pro,
DeepSeek-V4-Pro, Qwen3.5-397B-A17B, and Sonnet-4.6 (per-judge alt-test
in Tables~\ref{tbl-calderon-per-annotator-human} and
\ref{tbl-calderon-per-annotator-llm}). The central question is not
whether the LLM judge reproduces a single human grade, but whether its
deviation is comparable to that among human graders.

\section{Results}\label{results}

Unless otherwise noted, scores in this section are the LLM judge's
rubric scores, as 0--100 raw points or 0--18 German grade points. The
human-grading layer covers the 45-pick validation design with one
author-informed creator review and three blind reviews per pick (180
reviews total). The analysis pipeline regenerates every reported number
from the data file checked in alongside the manuscript.

\subsection{RQ1: Overall performance of LLM systems and
humans}\label{rq1-overall-performance-of-llm-systems-and-humans}

The unified per-system view across the three corpora is shown in
Table~\ref{tbl-main-leaderboard}; per-corpus full leaderboards with
surface-metric columns are in Appendix~\ref{full-results-table}. On the
Benchathon subset, top-tier closed systems score in the upper 60s on the
0--100 judge scale, with Opus-4.7 (69.3), Gemini-3.1-Pro (68.3), and
GPT-5.4 (68.2) clustered at the top with pass rates above 90\%, followed
by Gemini-3.1-Flash-Lite (63.5) and Sonnet-4.6 (58.9) in the upper 50s
to lower 60s. The flagship open-weight systems DeepSeek-V4-Pro and
Qwen3-235B trail the top closed models by roughly 13--28 raw points. The
same ordering broadly reproduces on ZJS, where GPT-5.4 leads at 60.4 raw
points (7.0 grade points, 78\% pass) and the weakest open-weight Llama-4
trails at 36.1 raw points (2.4 grade points, 4\% pass).

There is substantial within-task variance: per-system standard
deviations across the Benchathon tasks span roughly 8--17 raw points
across all tiers under the GPT-5.4-mini judge, so single-task
performance is a noisy signal even for top-tier systems. On the
Benchathon subset, the human cohort scores in the mid-range of the LLM
distribution under both conditions, with the co-creation condition
shifted upward (see human rows in Table~\ref{tbl-main-leaderboard} and
Figure~\ref{fig-human-vs-ai} in RQ4).

On the short-form Doctrinal Principles corpus the same flagship cluster
leads: Gemini-3.1-Pro (83.2), Opus-4.7 (83.1), Sonnet-4.6 (81.6), and
GPT-5.4 (80.3). Doctrinal Principles items carry a Ja/Nein (yes/no)
decision label; across systems accuracy ranges from 64\% to 77\%, with
Gemini-3.1-Pro at 77\% and Opus-4.7 at 75\%.

\begin{table*}[t]
\centering\footnotesize
\caption{Main leaderboard across the three corpora. Per-system mean LLM-judge raw score (0--100, mean\,$\pm$\,half-width of a 95\% CI: percentile bootstrap $B=2000$ on Benchathon for small per-system $n$, analytic 1.96\,$\cdot$\,SE on ZJS and Doctrinal Principles) and pass rate; Doctrinal Principles also reports Ja/Nein (yes/no) decision accuracy. Systems are ranked by the mean of their available per-corpus raw scores. The two human-baseline rows use the LLM judge's grades of human-written Benchathon solutions.}
\label{tbl-main-leaderboard}
\setlength{\tabcolsep}{4pt}
\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} l rrr rrr rrrr @{}}
\toprule
 & \multicolumn{3}{c}{Benchathon} & \multicolumn{3}{c}{ZJS} & \multicolumn{4}{c}{Doctrinal Principles} \\
\cmidrule(lr){2-4} \cmidrule(lr){5-7} \cmidrule(lr){8-11}
System / Group & $n$ & Raw & Pass & $n$ & Raw & Pass & $n$ & Raw & Pass & Acc. \\
\midrule
Opus-4.7 & 15 & 69.3\,$\pm$\,5.6 & 93\% & 652 & 58.0\,$\pm$\,1.0 & 74\% & 531 & 83.1\,$\pm$\,2.0 & 86\% & 75\% \\
Gemini-3.1-Pro & 15 & 68.3\,$\pm$\,8.4 & 93\% & 740 & 58.8\,$\pm$\,1.0 & 77\% & 531 & 83.2\,$\pm$\,1.8 & 87\% & 77\% \\
GPT-5.4 & 30 & 68.2\,$\pm$\,3.5 & 97\% & 586 & 60.4\,$\pm$\,1.1 & 78\% & 531 & 80.3\,$\pm$\,2.1 & 82\% & 74\% \\
Sonnet-4.6 & 15 & 58.9\,$\pm$\,6.0 & 73\% & 782 & 49.9\,$\pm$\,0.8 & 46\% & 531 & 81.6\,$\pm$\,2.1 & 83\% & 74\% \\
Gemini-3.1-Flash-Lite & 15 & 63.5\,$\pm$\,5.8 & 87\% & 579 & 44.6\,$\pm$\,0.8 & 26\% & 531 & 73.3\,$\pm$\,2.3 & 76\% & 71\% \\
GPT-5.4-mini & 15 & 58.6\,$\pm$\,5.5 & 73\% & 581 & 49.7\,$\pm$\,0.9 & 46\% & 531 & 71.8\,$\pm$\,2.4 & 72\% & 66\% \\
DeepSeek-V4-Pro & 15 & 56.1\,$\pm$\,5.9 & 67\% & 609 & 49.8\,$\pm$\,1.0 & 44\% & 531 & 73.5\,$\pm$\,2.3 & 73\% & 67\% \\
DeepSeek-V4-Flash & 15 & 49.3\,$\pm$\,3.8 & 47\% & 582 & 45.9\,$\pm$\,0.8 & 30\% & 530 & 70.7\,$\pm$\,2.4 & 73\% & 64\% \\
Qwen3.5-122B & 15 & 49.4\,$\pm$\,4.9 & 40\% & 863 & 41.3\,$\pm$\,0.7 & 19\% & 526 & 69.8\,$\pm$\,2.4 & 75\% & 73\% \\
Qwen3.6-35B & 15 & 42.4\,$\pm$\,7.2 & 27\% & 829 & 37.9\,$\pm$\,0.7 & 11\% & 531 & 69.5\,$\pm$\,2.5 & 69\% & 68\% \\
Llama-4 & 15 & 37.8\,$\pm$\,4.1 & 20\% & 581 & 36.1\,$\pm$\,0.6 & 4\% & 531 & 70.1\,$\pm$\,2.3 & 75\% & 69\% \\
Qwen3-235B & 28 & 41.3\,$\pm$\,4.3 & 18\% & 656 & 35.3\,$\pm$\,0.7 & 5\% & 531 & 67.3\,$\pm$\,2.5 & 69\% & 70\% \\
\midrule
Human (all) & 220 & 61.1\,$\pm$\,2.1 & 77\% & --- & --- & --- & --- & --- & --- & --- \\
\quad traditional & 65 & 50.0\,$\pm$\,3.5 & 52\% & --- & --- & --- & --- & --- & --- & --- \\
\quad co-creation & 155 & 65.7\,$\pm$\,2.2 & 88\% & --- & --- & --- & --- & --- & --- & --- \\
\bottomrule
\end{tabular*}
\end{table*}

\subsection{RQ2: Scaling and system
effects}\label{rq2-scaling-and-system-effects}

Closed flagship systems from OpenAI, Anthropic, and Google occupy the
top of every per-corpus leaderboard, while efficiency-tier closed
systems and the strongest open-weight systems (DeepSeek-V4-Pro,
Qwen3-235B) form an overlapping mid-band - closed-API dominance narrows
substantially below the flagship tier. Aggregating by tier, the
flagship-vs-open-weight gap is 21 raw points on Benchathon and narrows
to 16 on ZJS; the closed-vs-open weights gap shrinks similarly from 20
to 13 raw points. The same direction holds on Doctrinal Principles, so
the flagship-vs-open-weight ordering survives the three different task
formats and the 4-dimension rubric variant. We frame these as
system-level rather than model-level effects, since black-box API access
entangles the open--closed split with provider-side prompts, decoding,
post-processing, and possible retrieval or tool use (see Limitations).

\subsection{RQ3: Evaluation validity - automatic metric
correlation}\label{rq3-evaluation-validity---automatic-metric-correlation}

Across all three corpora, lexical surface metrics correlate with the LLM
judge's rubric raw score more strongly than embedding-based metrics,
running partly against the common expectation that semantic-embedding
metrics dominate lexical ones on long-form legal text. On Benchathon,
METEOR (r=+0.61), ROUGE (r=+0.68), and BLEU (r=+0.58) lead while
MoverScore (r=+0.59), BERTScore (r=+0.47), and sentence-embedding
similarity (r=+0.33) trail; the same ordering broadly holds on ZJS and
Doctrinal Principles
(Appendix~\ref{automatic-metric-vs.-llm-judge-correlation}:
Table~\ref{tbl-metric-correlation},
Figure~\ref{fig-metric-correlation}). This is consistent with the highly
templated structure of doctrinal German exam writing, where reference
and high-quality system answers share substantial n-gram material around
statutory citations and the
\emph{Obersatz--Definition--Subsumtion--Ergebnis} scaffolding. At the
per-system level on Benchathon, the lexical metrics' Spearman against
the judge ranking reaches +0.60 (METEOR) while BERTScore (+0.80) and
semantic similarity (+0.77) trail - a leaderboard built on a strong
lexical metric would broadly preserve the judge's coarse-tier ordering
but disagree on the mid-tier, motivating a calibrated LLM judge as the
primary scoring instrument.

\subsection{RQ4: Human--AI co-creation under LLM-judge
scoring}\label{rq4-humanai-co-creation-under-llm-judge-scoring}

\begin{figure}[t]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{manuscript_files/figure-pdf/fig-human-vs-ai-output-1.pdf}}

}

\caption{\label{fig-human-vs-ai}Mean LLM-judge raw score (0--100) per
group on the Benchathon validation subset, with 95\% bootstrap CIs on
each group's mean. The two AI bars pool per-generation scores across all
evaluated LLM systems (\emph{pooled}) and across the closed-flagship
tier only (\emph{flagship}).}

\end{figure}%

Co-creation solutions score higher than traditional ones on the
Benchathon - by +15.7 raw points on average, about +2.8 grade points on
the 0--18 scale (Figure~\ref{fig-human-vs-ai}; participant-clustered
95\% CI {[}+9.2, +22.2{]}). The gap holds within the 23 participants who
completed both arms, repeats across all three legal domains, and is in
fact a lower bound on the per-participant gain because less-experienced
participants skipped traditional items more often than co-creation ones
- leaving the traditional pool expertise-biased upward (full robustness
arc in Appendix~\ref{rq4-supplementary}). At that level the AI-assisted
humans sit alongside the best standalone LLMs we evaluated: a TOST
equivalence test rules out any difference of more than \(\pm 5\) raw
points against the closed-flagship tier
(Table~\ref{tbl-main-leaderboard}). The one substantive caveat is on
magnitude - when the same solutions are re-graded by blind human
reviewers on the RQ5 validation subset, the gap shrinks to about 13 raw
points, +2 points smaller than the LLM-judge estimate, a small absolute
discrepancy consistent with the GPT-5.4-mini judge's near-zero
content-dependent calibration offset and within the blind-pool's
inter-rater spread (Limitations).

\subsection{RQ5: Grading reliability}\label{rq5-grading-reliability}

The reliability question for the leaderboard is whether the LLM judge
can stand in for a blind human reviewer. We answer it in three stages:
how closely the judge agrees with humans on a per-solution basis,
whether it clears the formal substitution bar, and what its
disagreements look like when they happen.

Across the validation subset, the primary GPT-5.4-mini judge agrees with
the per-solution mean of the blind reviewers at Pearson r=0.76,
pass/fail Cohen's \(\kappa\)=0.60, and MAE 10.8 raw / 2.7 grade points,
with a per-solution offset of just -0.0 raw points (so the
bias-corrected MAE is essentially unchanged at 10.8 / 2.6). The
reviewers themselves disagree by an average within-annotation max--min
spread of 23.9 raw points - comparable to the several-grade-point range
Hufeld \citep{hufeld2024} documents for German legal grading - and the
pool reaches ICC(2,\(k\))=0.84, so the judge sits inside the cloud of
human disagreement rather than outside it (full agreement panel -
Spearman, by-provenance ICCs, balanced rater-triplet for the
partially-crossed design - in Table~\ref{tbl-agreement}).

Per-solution agreement does not by itself establish that the judge can
\emph{replace} a randomly drawn reviewer. The Calderon alt-test sets a
stricter bar at \(\varepsilon=0.15\) with Benjamini-Yekutieli FDR
(§\ref{sec-human-eval}); we apply it across six judge families - the
primary GPT-5.4-mini, plus Opus-4.7, Gemini-3.1-Pro, DeepSeek-V4-Pro,
Qwen3.5-397B-A17B, and Sonnet-4.6. Two judges clear the
\(\omega \geq 0.5\) replacement bar on the human-authored picks:
GPT-5.4-mini at \(\omega=\) 0.60 and Opus-4.7 at \(\omega=\) 0.60. The
two judges from independent providers reject the same blind reviewers as
the ones they can statistically replace, despite originating from
completely different model families - a convergence that argues against
same-provider judge bias as a meaningful confound. Sonnet-4.6
(\(\omega=\) 0.40) and Gemini-3.1-Pro (\(\omega=\) 0.40) are one
annotator-rejection short of the bar; DeepSeek-V4-Pro and
Qwen3.5-397B-A17B fail at \(\omega \leq 0.20\). The expert-reference
variant against the un-blind creator additionally passes for the primary
GPT-5.4-mini judge on human picks (\(\omega=\) 0.60 at
\(\varepsilon=0.20\)) but fails on LLM picks (\(\omega=\) 0.00)
(Table~\ref{tbl-agreement}; per-judge \(\omega\), per-annotator
\(p\)-values, and a stacked-bootstrap robustness check in
Appendix~\ref{sec-judge-calibration-supplementary-detail}). The judges
that fail the replacement bar cluster among those whose per-solution
offset against the human pool is largest - a calibration gradient
(Appendix~\ref{sec-judge-calibration-supplementary-detail}).

The disagreement is also patterned by rubric dimension
(Figure~\ref{fig-rubric-dim}): agreement is highest on dimensions with
structured scoring criteria and lowest on presentation and form. Several
outcome-and-reasoning dimensions drop on LLM-generated solutions -
Result correctness from r=0.76 (human-authored) to r=0.62 (LLM), with
comparable drops on Issue identification, Doctrinal knowledge, and
Problem depth - consistent with judge--human divergence on outcomes
reached via unfamiliar reasoning paths.

Re-running GPT-5.4-mini \(k=3\) times on the Benchathon LLM generations
yields a within-cell stdev of 3.45 raw points, substantially tighter
than the inter-human within-solution spread of 23.9 raw points - so the
calibration offset is not noise the judge could re-roll out of. Across
the six judge families on the 258-generation subset, the strictness
gradient (Opus-4.7 strictest, Qwen3.5-397B-A17B most lenient;
Table~\ref{tbl-judge-calibration}) leaves pairwise rank agreement at
Spearman \(\rho\) between 0.78 and 0.96 across all fifteen pairs, and
\(\omega\) drops, not rises, from human to LLM picks for every judge -
arguing against same-family inflation.

\subsection{Error analysis}\label{error-analysis}

A qualitative inspection of the LLM-generated solutions surfaces five
recurring failure modes - patterns the rubric flags but a single-number
metric would miss. The most common is \emph{correct outcome, weak
subsumption} - 9 instances, concentrated in the open-weight mid-tier,
where the doctrinally expected conclusion is reached via abstract
argumentation rather than fact-bound \emph{Subsumtion}. A related
length-bound pair surfaces around \emph{Subsumtion} itself:
\emph{missing or perfunctory subsumption in short answers} in 16
generations below 200 words where the answer labels rather than
subsumes, and a complementary \emph{long-but-shallow} pattern in two
generations exceeding 2,200 words with weak Subsumption quality and
Problem depth, where lexical metrics over-reward what the rubric does
not. Finally, \emph{wrong-norm framing} - low Legal grounding and
Doctrinal knowledge together, indicating an unsuitable doctrinal frame
rather than misexecution within the correct one - is documented
qualitatively without a global count. The cleanest pointer at
judge-failure cases is a fifth pattern, \emph{wrong outcome despite
plausible reasoning}: 5 instances where the judge praises fact-bound
\emph{Subsumtion} (\(\geq 0.60\cdot\text{max}\)) but the final answer is
wrong. A judge that conflated reasoning and outcome would be visible
here as systematic praise of reasoning preceding a wrong result, so the
rubric's separation of those two dimensions is doing real work. Patterns
are identified by high within-rubric dimension dispersion combined with
at least one dimension below \(0.40\cdot\text{max}\), against a
denominator of 208 LLM-system generations, and are reported
descriptively without multiple-comparison correction; representative
task identifiers, dimension scores, and judge-justification quotes are
available in the released analysis pipeline.

\section{Discussion}\label{discussion}

Capability is concentrated in the closed-flagship tier, but the margin
is jurisdiction- and length-sensitive. Across the three corpora the top
of the leaderboard is consistently occupied by Opus-4.7, Gemini-3.1-Pro,
and GPT-5.4, with Sonnet-4.6 joining on Doctrinal Principles. The
flagship-vs-open-weight gap is \textasciitilde21 raw points on
Benchathon, narrows to \textasciitilde16 on ZJS, and shrinks further on
Doctrinal Principles. The strongest open-weight systems
(DeepSeek-V4-Pro, Qwen3-235B) overlap the efficiency-tier closed band on
the longer corpora and reach within a few points of the flagships on the
short one, so the practical question for German legal NLP is not whether
open-weight systems can be used, but whether the residual flagship
advantage is paid for by the cost and access constraints in
Appendix~\ref{operational-metadata}.

Lexical surface metrics beat embedding metrics, but neither replaces a
rubric judge. Across all three corpora BLEU, ROUGE, and METEOR correlate
with the rubric judge more strongly than BERTScore, MoverScore, or
sentence-similarity (METEOR r=+0.61 vs.~BERTScore r=+0.47 on Benchathon,
reproducing on ZJS and Doctrinal Principles;
Appendix~\ref{automatic-metric-vs.-llm-judge-correlation}). This runs
against the expectation that semantic-embedding metrics dominate lexical
ones on long-form text, and is most parsimoniously explained by the
templated structure of doctrinal German exam writing - high-quality
answers share substantial n-gram material around statutory citations and
the \emph{Obersatz--Definition--Subsumtion--Ergebnis} scaffold. A
lexical-only leaderboard would preserve the coarse tier ordering but
disagree on the mid-tier, so the rubric judge remains the primary
instrument and surface metrics read as cheap correlates.

Human--AI co-creation lifts unaided humans into the closed-flagship
band, with a magnitude caveat. AI-assisted human work scores +15.7 raw
points (≈ +2.8 German grade points) above unaided human work under the
judge, a gap that holds within the 23 participants who completed both
arms and across the three legal areas; a TOST equivalence test rules out
any difference of more than \(\pm 5\) raw points against the
closed-flagship LLM tier (Appendix~\ref{rq4-supplementary}). Blind-human
re-grading on the RQ5 subset shrinks the gap to +13.6 raw points,
narrowing the headline by \textasciitilde2 points; direction and
qualitative conclusion are unchanged, and the residual sits within
blind-pool inter-rater spread.

Two judges from independent providers clear the substitution bar. The
primary GPT-5.4-mini judge tracks the per-solution blind-reviewer mean
at Pearson r=0.76 and pass/fail \(\kappa\)=0.60 and sits inside the
human disagreement cloud (ICC(2,\(k\))=0.84). On the Calderon alt-test
at \(\varepsilon=0.15\), GPT-5.4-mini and Opus-4.7 both clear the
\(\omega \geq 0.5\) substitution bar on human-authored picks
(\(\omega=\) 0.60 and 0.60) and reject the same blind reviewers; the
other four (Sonnet-4.6, Gemini-3.1-Pro, DeepSeek-V4-Pro,
Qwen3.5-397B-A17B) fall short along a content-dependent leniency
gradient documented in
Appendix~\ref{sec-judge-calibration-supplementary-detail}. Inter-judge
Spearman across the six families stays between 0.78 and 0.96, so the
RQ1--RQ2 ordering survives any single judge's absolute-score bias. The
convergence of two judges from independent providers - on both the bar
and the specific reviewers they replace - argues against same-provider
bias as a meaningful confound; an Opus-anchored cross-check of the
primary scores is a natural absolute-calibration follow-up. Where the
judge still diverges, the disagreement concentrates on presentation and
on outcomes reached via unfamiliar reasoning paths (highest agreement on
Result correctness r=0.76 and Issue identification r=0.80; lowest on
Formal correctness r=0.29 and Terminology r=0.13; Result-correctness
Pearson drops to r=0.62 on LLM-generated solutions) - supporting LLM
judges as scalable raters alongside humans rather than standalone ground
truth, with judge-model choice treated as a deliberate calibration knob.

\section{Conclusion}\label{conclusion}

We introduce the BenGER dataset for subsumption-based legal reasoning in
German law, combining two exam-style corpora (ZJS, Benchathon) with a
short doctrinal-reasoning corpus (Doctrinal Principles), a Benchathon
validation subset with human and human--AI baselines, a rubric-aligned
LLM-as-a-Judge, and a multi-rater cross-validation protocol - 12 systems
and 14614 generations on Benchathon, ZJS, and Doctrinal Principles, all
run end-to-end on our previously released BenGER platform
\citep{nagl2026benger}. BenGER is released as an open evaluation
framework with corpora, judge prompts, rubric, and analysis pipeline at
\url{https://github.com/SebastianNagl/benger-platform}.

\section*{Limitations}\label{limitations}
\addcontentsline{toc}{section}{Limitations}

Several limitations bound our findings:

All LLM systems are evaluated through hosted provider APIs in a
black-box setting, so reported scores reflect end-to-end deployed
behaviour, not isolated base-model capability. We do not vary
provider-side prompts, decoding configurations, retrieval, or tool use,
and so avoid claims about the contribution of individual architectural
choices.

The dimension rubric and the LLM-judge prompt were co-developed for this
benchmark rather than adopted from independent prior work; we validate
them as a pair against the multi-rater human-grading layer (RQ5), whose
within-annotation inter-rater spread (5.2 grade points) sits within the
range Hufeld \citep{hufeld2024} documents for German legal grading.
Neither component has been validated in isolation.

The Benchathon subset comprises 15 tasks and a modest participant pool.
This suffices for the per-task, per-system comparisons and the judge
validation reported here, but limits statistical power for fine-grained
interaction effects such as expertise-stratified co-creation analyses.

Judge bias is a known confounder in LLM evaluation
\citep{zheng2023mtbench, panickssery2024self}; we address it via the
multi-rater agreement protocol on the Benchathon validation subset (RQ5)
and the inter-judge agreement analysis across six families
(GPT-5.4-mini, Opus-4.7, Gemini-3.1-Pro, DeepSeek-V4-Pro,
Qwen3.5-397B-A17B, Sonnet-4.6), which shows a clear strictness gradient
but pairwise rank agreement comparable to inter-human agreement.
Same-provider preference is a specific structural risk in BenGER because
the primary judge GPT-5.4-mini shares a model family with
leaderboard-leading GPT-5.4 and GPT-5.4-mini systems, and Sonnet-4.6
(Benchathon cross-validation judge) shares its family with
leaderboard-leading Opus-4.7 and Sonnet-4.6 systems. Five signals limit
its plausible size: (i) the two judges that clear the Calderon
replacement bar - GPT-5.4-mini and Opus-4.7 - originate from independent
providers and reject the same three blind reviewers as the ones they can
statistically replace, a convergence that is hard to attribute to family
preference; (ii) cross-judge Spearman across six judge families holds
the system ordering across providers; (iii) judge--human Pearson is
\emph{lower} on the LLM half (r=0.64 vs.~r=0.76) - the opposite of
same-family inflation; (iv) Calderon \(\omega\) drops from 0.60 (human)
to 0.00 (LLM) - same direction; (v) the LLM-pick ω drop appears across
all six judge families tested - closed and open-weight, including the
ones whose families lead the system rankings - so the lift is
judge-model-broad rather than family-aligned
(Tables~\ref{tbl-judge-calibration},~\ref{tbl-calderon-per-annotator-human},~\ref{tbl-calderon-per-annotator-llm}).
An Opus-anchored re-score would only be needed for absolute-calibration
claims; RQ1--RQ2 makes none.

Per-annotator \(n_j \in [7, 21]\) is well below Calderon's recommended
50--100, so every test fell back to Wilcoxon with reduced power
(computed under the exact permutation distribution so the reported
\(p\)-values are stable across SciPy versions). Absolute RQ1--RQ2
leaderboard scores carry the GPT-5.4-mini calibration offset
(Table~\ref{tbl-judge-calibration}; measured against both the
blind-reviewer pool mean and an independent creator-anchored reference
in Appendix~\ref{sec-creator-anchored-calibration}) and should be read
as a calibrated ordering rather than human-pool estimates. Calderon's
FAQ Q12 recommends per-domain \(\omega\), but per-area \(n_j\) would
drop to 3--7, so we pool across the three legal areas (\emph{Bereiche}:
civil, public, and criminal law).

The rubric is grounded in German doctrinal grading conventions and is
not designed to generalise to common-law or non-German civil-law
systems; metrics and aggregate scores in the BenGER dataset should not
be transferred to other jurisdictions without re-calibration.

ZJS material is publicly indexed, so provider models may have
encountered some of it during pretraining; we have not run an explicit
memorisation probe. The agreement between the ZJS ordering and the
orderings on the private Benchathon and Doctrinal Principles corpora
bounds \emph{catastrophic} differential contamination - a
memorisation-driven system would visibly fall out of order on the unseen
corpora - but is consistent with both low contamination and
contamination that scales proportionally across systems.

Per-domain CIs (RQ4), pairwise inter-judge correlations (RQ5), and
Error-analysis patterns are reported descriptively; we do not draw
inferential claims from individual cell-level comparisons.

The Benchathon and ZJS exam-style corpora are graded with the
10-dimension case-solution (\emph{Falllösung}) rubric, while the
short-form Doctrinal Principles corpus uses a 4-dimension rubric (result
correctness, legal knowledge, subsumption, clarity); per-dimension
comparisons across corpora are therefore not meaningful, and only
aggregate raw scores, pass rates, and Ja/Nein (yes/no) accuracy
(Doctrinal Principles only) should be compared across the three.

The Google efficiency-tier slot was generated with two distinct Google
models - Gemini-3-Flash on the Benchathon subset and
Gemini-3.1-Flash-Lite (a separate efficiency product line rather than a
successor release of Flash) on the ZJS and Doctrinal Principles corpora
- because the model set was finalised between the two generation runs.
We treat them as the same conceptual tier slot for tier-level
comparisons and disclose the raw model ids in
Table~\ref{tbl-system-overview}; row-level cross-corpus comparison for
this slot should be read with the model drift in mind, and tier-level
claims should not be read as a per-model claim about either Flash or
Flash-Lite alone.

\section*{Ethical considerations}\label{ethical-considerations}
\addcontentsline{toc}{section}{Ethical considerations}

Benchathon participants were recruited from a pool of law students and
recent graduates who consented to the use of their written solutions and
self-reported expertise data for research purposes. Solutions and
self-reports are anonymized in the released BenGER dataset. Human
grading is conducted by domain experts under the same consent regime; we
release dimension-level rubric scores and aggregate statistics, not
free-text feedback that could re-identify a participant. The Benchathon
study design for human and co-creation baseline was approved by an
ethics committee. The LLM-as-a-Judge methodology in BenGER is intended
for research-scale evaluation of legal-reasoning systems and is not
validated for use as a graded assessment instrument in legal education
or for deployment in legal practice.

The ZJS exams and reference solutions are copyright-protected. We have
cleared IP rights for the vast majority of items, which are bundled
directly with the released dataset; for the remainder we provide URL
pointers to publicly accessible free locations on the web. All model
generations and LLM-judge evaluation scores are released without
restriction. The benchmark is therefore end-to-end reproducible -
recomputing any reported number requires only a short fetch step for the
IP-uncleared ZJS items.

A public legal-reasoning benchmark can be optimised against, so future
systems may improve on the benchmark without commensurate gains in real
legal-reasoning quality. To mitigate this risk we release the rubric and
judge prompts alongside the data, encourage reporting on the full
per-dimension breakdown rather than a single headline score, and treat
the benchmark as one signal among several in the evaluation of
legal-domain LLMs.

\section*{AI usage}\label{ai-usage}
\addcontentsline{toc}{section}{AI usage}

The authors leveraged Anthropic Claude Opus 4.7 for coding tasks and
OpenAI GPT-5.5 Pro for wording and LaTeX assistance.

\section*{Acknowledgments}\label{acknowledgments}
\addcontentsline{toc}{section}{Acknowledgments}

We thank our colleagues in the TITAN project group - Philipp Reuß
(University of Göttingen), Sarah Rachut (TU Braunschweig), Liane Wörner
(University of Konstanz), Dominik Brodowski (Saarland University), and
Markus Langer and Asya Caroei (both University of Freiburg) - for the
discussions that shaped this work. We are grateful to the Legal Tech
Verband (LTV) and its members Clemens Hufeld (Beck/Noxtua), Daniella
Domokos (Capgemini), Ben Kühnel (Forvis Mazars), and Katharina Hertel
(Recode Law) for their support in organising the Benchathon, and to all
Benchathon participants for their dedicated work. We thank Markus Wagner
and the \emph{Zeitschrift für das Juristische Studium} (ZJS) author
community for generously permitting use and redistribution of their
cases. Finally, we thank Peter Moser (LMU) for connecting us with the
right experts and materials.

BenGER is generously funded by the Daimler Benz Foundation as part of
project TITAN (\emph{Technologische Intelligenz zur Transformation,
Automatisierung und Nutzerorientierung des Justizsystems}) and by the
German Federal Ministry of Justice as part of the
\emph{Digitalisierungsinitiative des Bundes für die Justiz} under the
GSJ project (\emph{Generatives Sprachmodell der Justiz}), a
collaboration between the justice ministries of North Rhine-Westphalia
and Bavaria, TU Munich, and the University of Cologne.

\bibliography{references.bib}
\appendix
\nolinenumbers

\section*{Contents of the Appendix}
\noindent
A\quad Full results table \dotfill \pageref{full-results-table}\par
B\quad Operational metadata \dotfill \pageref{operational-metadata}\par
C\quad Evaluated systems catalogue \dotfill \pageref{evaluated-systems-catalogue}\par
D\quad Per-task per-system heatmap \dotfill \pageref{per-task-per-system-heatmap}\par
E\quad Benchathon participant composition \dotfill \pageref{benchathon-participant-composition}\par
F\quad Full Benchathon human-evaluation assignment procedure \dotfill \pageref{full-benchathon-human-evaluation-assignment-procedure}\par
G\quad RQ4 supplementary detail \dotfill \pageref{rq4-supplementary}\par
H\quad Automatic-metric vs.\ LLM-judge correlation \dotfill \pageref{automatic-metric-vs.-llm-judge-correlation}\par
I\quad Judge--human agreement statistics \dotfill \pageref{judgehuman-agreement-statistics}\par
J\quad System prompts for generation \dotfill \pageref{system-prompts-for-generation}\par
K\quad Instruction prompts for generation \dotfill \pageref{instruction-prompts-for-generation}\par
L\quad Evaluation prompts for the LLM judge \dotfill \pageref{evaluation-prompts-for-the-llm-judge}\par
M\quad LLM-judge configuration \dotfill \pageref{llm-judge-configuration}\par
N\quad Judge calibration -- supplementary detail \dotfill \pageref{sec-judge-calibration-supplementary-detail}\par
O\quad Responsible NLP Research Checklist \dotfill \pageref{responsible-nlp-research-checklist}\par
% BLIND-REVIEW SWAP: comment out the line above (prefix it with %); the
% ARR submission form carries the checklist content separately.

\section{Full results table}\label{full-results-table}

The full per-system leaderboards are split into six tables, three
corpora \(\times\) two metric groups: rubric-based metrics (LLM-judge
raw / grade-points / pass rate; plus human-grader rubric columns on
Benchathon) in
Tables~\ref{tbl-full-results-rubric-benchathon},~\ref{tbl-full-results-rubric-zjs},~\ref{tbl-full-results-rubric-grundpr},
and surface / embedding-based automatic metrics (plus Doctrinal
Principles Ja/Nein decision accuracy, a task-correctness measure rather
than a rubric one) in
Tables~\ref{tbl-full-results-auto-benchathon},~\ref{tbl-full-results-auto-zjs},~\ref{tbl-full-results-auto-grundpr}.
The two Benchathon human-baseline rows (traditional, co-creation) are
pinned at the top of the Benchathon tables. The CI is the percentile
interval over \(B=2000\) resamples on the per-generation values (seed
\(42\)); each cell shows the mean stacked above \(\pm\) half the width
of the 95\% CI (in a smaller font). Empty cells indicate the metric is
not computed on that dataset. Derived from the released analysis
pipeline.

\input{assets/tbl_full_results_rubric_benchathon.tex}
\input{assets/tbl_full_results_rubric_zjs.tex}
\input{assets/tbl_full_results_rubric_grundpr.tex}
\input{assets/tbl_full_results_auto_benchathon.tex}
\input{assets/tbl_full_results_auto_zjs.tex}
\input{assets/tbl_full_results_auto_grundpr.tex}

\section{Operational metadata}\label{operational-metadata}

Table~\ref{tbl-system-cost} reports per-system operational metadata for
the Benchathon generation run: mean cost per generation, mean wall-clock
response time, mean output length, and the count of truncated
generations out of total. Cost is taken from the per-call
\texttt{response\_metadata} recorded at generation time; aggregates are
over the same generation pool reported in the main leaderboards.

\input{assets/tbl_system_cost.tex}

\section{Evaluated systems catalogue}\label{evaluated-systems-catalogue}

Table~\ref{tbl-system-overview} catalogues the LLM systems evaluated in
this work alongside their provider family, the short alias used
throughout the body of the paper, the full model id, tier classification
(closed flagship, efficiency-oriented, or open-weight reference),
weights status (open vs.~closed), the decoding temperature and
max-output-tokens setting used, the total generation count on the
Benchathon subset, and the count of truncated generations over that
total.

\input{assets/tbl_system_overview.tex}

\section{Per-task per-system heatmap}\label{per-task-per-system-heatmap}

Figure~\ref{fig-task-system-heatmap} visualises the per-task per-system
mean LLM-judge raw score on the Benchathon subset. Rows are systems
ordered by overall mean (top = highest); columns are the 15 Benchathon
tasks ordered by inner identifier and grouped by legal area (Civ = civil
law, Pub = public law, Crim = criminal law). The heatmap exposes the
within-task variance discussed in RQ1: top-tier closed systems hold a
tighter per-task spread, while mid-tier and smaller open-weight systems
show visibly larger task-to-task swings for the same overall mean.

\begin{figure*}[!t]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{manuscript_files/figure-pdf/fig-task-system-heatmap-output-1.pdf}}

}

\caption{\label{fig-task-system-heatmap}Per-task per-system mean
LLM-judge raw score on the Benchathon subset. Rows are systems ordered
by overall mean (top = highest). Columns are the 15 Benchathon tasks
ordered by inner\_id, grouped by legal area (Civ = civil law, Pub =
public law, Crim = criminal law).}

\end{figure*}%

\section{Benchathon participant
composition}\label{benchathon-participant-composition}

The Benchathon validation cohort comprises the participants who together
produced the human solutions and reviews used throughout this paper.
They self-reported their legal-expertise level on a four-stage scale
corresponding to standard stages of German legal education and practice:
\textbf{layperson} (no formal legal training), \textbf{law student}
(currently enrolled in a German law program, typically working toward
the first state examination - \emph{Erstes Staatsexamen}),
\textbf{graduated} (completed legal studies but not currently in legal
practice or \emph{Referendariat}), and \textbf{\emph{Referendar}} (in
the approximately two-year practical legal traineeship that follows the
first state examination and precedes the second state examination, after
which a candidate becomes a fully qualified \emph{Volljurist}).
Table~\ref{tbl-human-participants} breaks the cohort down by
self-reported level and working condition (traditional vs.~human--AI
co-creation), counting both unique participants and annotation
contributions per condition.

\input{assets/tbl_human_participants.tex}

\section{Full Benchathon human-evaluation assignment
procedure}\label{full-benchathon-human-evaluation-assignment-procedure}

The validation subset comprises 45 solutions (15 Benchathon tasks × 3
provenances: human-traditional, human--AI co-creation, LLM-generated).
For each task and condition, the human pick is the participant whose
\emph{expertise proxy} - a z-score combining self-assessed competence in
the relevant legal area and, where available, the first state
examination grade - is closest to the median expertise score of all
participants in that legal area and condition. LLM picks are drawn
through a deterministic rotation across three system tiers (closed
flagship, efficiency-oriented, open-weight reference) with a per-system
load counter that spreads picks across systems within each tier so the
validation set covers as many distinct systems as the available pool
permits; generations shorter than 200 output tokens are excluded.

Each selected solution receives one creator review by the author of the
corresponding task and up to three independent blind reviews (design
target: 180 reviews - 45 creator + 135 blind). Blind reviews are
assigned such that each solution is targeted for three distinct graders,
while task authors do not blindly evaluate solutions from their own
authored legal area. In practice, three graders contribute exclusively
as blind reviewers across all three legal areas, and the two
criminal-law creators additionally contribute blind reviews on civil-law
and public-law solutions. The assignment procedure balances reviewer
workload and monitors coverage across solution provenance, legal domain,
and task difficulty. Blind graders are unaware of solution origin -
i.e., whether a solution was written traditionally, produced in
human--AI co-creation, or generated by an LLM - and grade against the
same rubric as the LLM judge, including both total and dimension-level
scores. Creator reviews are reported as an author-informed reference
signal and are not included in inter-rater reliability estimates. The
IRR statistics in Table~\ref{tbl-agreement} are computed on the full k=3
blind-rater pool over all 45 picks.

\paragraph{Roster composition and Calderon $\varepsilon$ choice.} The
full grading roster is seven people; the \(m=5\) blind subset used in
the Calderon blind-pool alt-test reflects the graders who performed at
least one blind review, while the remaining two contributed only
creator-role reviews and constitute the single-expert reference. Two of
the \(m=5\) blind reviewers additionally performed creator reviews on
disjoint solution subsets (overlap zero by design), so no solution had
the same person in both roles. We use Calderon's ``skilled annotator''
cost-benefit penalty \(\varepsilon=0.15\) for the blind-pool procedure,
matching the law-students-around-1st-state-exam profile
(§\ref{sec-human-eval}); for the single-expert variant we additionally
report \(\varepsilon=0.20\) as a conservative sensitivity against an
expert-tier reading of the un-blind creator reference. At the sample
sizes available here both \(\varepsilon\) values yield the same
single-expert decision.

\section{RQ4 supplementary detail}\label{rq4-supplementary}

This appendix collects the robustness checks, per-domain breakdown, TOST
machinery, and blind-human small-n cross-check that support the
four-sentence RQ4 body summary. Every number here is also exported in
machine-readable form under \texttt{assets/rq4/} (one CSV per analytic
step, see \texttt{assets/rq4/README.md}).

\paragraph{Imbalance and skip mechanism.} The per-arm imbalance (155 vs.
65 annotations across 33 vs 23 participants) reflects a skip mechanism
in the protocol: participants could decline any item, and
less-experienced participants skipped traditional items more often (full
per-expertise-stratum breakdown in
Appendix~\ref{benchathon-participant-composition}). The traditional pool
is therefore expertise-biased upward relative to the co-creation pool,
so the headline Δ in the body is a \emph{lower} bound on the
per-participant co-creation gain - a forced-completion design would
widen the gap, not narrow it.

\paragraph{Robustness across resampling units.} The body quotes the
participant-clustered bootstrap as the headline.
Table~\ref{tbl-rq4-bootstraps} reports the same Δ under three additional
resampling units to verify the effect is not an artifact of the chosen
unit of inference. All four point estimates agree on the sign and
within-rounding magnitude; the participant-clustered interval is the
widest (correctly recognising that annotations cluster on participant)
and is the one we quote in body and Discussion.

\input{assets/tbl_rq4_bootstraps.tex}

\paragraph{Per-domain Δ.} Per-Bereich Δ values, descriptive only - with
three legal areas, \(n \leq 53\) per condition per area, and no
pre-registered domain-level hypothesis we do not run inferential tests
of domain-level contrasts; we report Table~\ref{tbl-rq4-by-bereich} to
verify the direction is consistent across all three.

\input{assets/tbl_rq4_by_bereich.tex}

\paragraph{TOST equivalence vs the closed-flagship tier.} Two one-sided
bootstrap tests against a \(\pm 5\)-raw-point equivalence band (≈
\(\pm 0.9\) grade points). The co-creation mean (65.7) sits -0.9 raw
points from the closed-flagship-tier mean (66.6, 95\% CI {[}63.6,
69.3{]}); one-sided 95\% bounds on the difference are {[}-3.9, +2.2{]}.
Both bounds lie inside the \(\pm 5\) band, so we reject both
\(\Delta \leq -5\) and \(\Delta \geq +5\) - co-creation is statistically
equivalent to the closed-flagship tier within the \(\pm 5\)-raw-point
band.

\paragraph{Blind-human cross-check.} On the 15 traditional + 15
co-creation solutions in the RQ5 validation subset (n=10+11
participants), the blind-human mean Δ is +13.6 raw points
(participant-clustered 95\% CI {[}-1.4, +30.5{]}; spans zero at this
\(n\)). The sign matches the judge result; the gap to the primary
GPT-5.4-mini judge's +15.7-raw-point estimate (+2.1 raw points) is small
in both absolute and relative terms, consistent with GPT-5.4-mini's
near-zero content-dependent calibration offset
(Table~\ref{tbl-judge-calibration}:
\(\bar{\Delta}_{\text{dir}} \approx 0\) on human-content picks and
\(\approx -0.5\) on LLM-content picks, neither significantly different
from the pool). The blind-human and LLM-judge estimates of the
co-creation gain therefore agree at this sample size, within the
inter-rater noise of the blind-pool itself.

\section{Automatic-metric vs.~LLM-judge
correlation}\label{automatic-metric-vs.-llm-judge-correlation}

Table~\ref{tbl-metric-correlation} gives the per-generation Pearson
\(r\) between every automatic metric and the LLM-judge raw score across
the three LLM-generation corpora and the two Benchathon human-annotation
conditions; Figure~\ref{fig-metric-correlation} repeats the same
comparison as a 1×3 panel of per-corpus Pearson and Spearman bar plots
(Benchathon \textbar{} ZJS \textbar{} Doctrinal Principles).

\begin{table*}[t]
\centering\footnotesize
\caption{Per-generation Pearson $r$ between each automatic metric and the LLM judge's raw score across three corpora of LLM generations and the Benchathon human-annotation working conditions (traditional vs. human--AI co-creation). Cell format: $r$ ($n$). `---' = metric not run on that corpus / condition. Rows are in a fixed canonical order (lexical $\rightarrow$ embedding).}
\label{tbl-metric-correlation}
\setlength{\tabcolsep}{4pt}
\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}lccccc@{}}
\toprule
Metric & \shortstack{Benchathon\\(LLM)} & \shortstack{ZJS\\(LLM)} & \shortstack{Grundpr.\\(LLM)} & \shortstack{Bench.\,human\\\textit{traditional}} & \shortstack{Bench.\,human\\\textit{co-creation}} \\
\midrule
BLEU & $+0.58$ {\scriptsize ($n{=}208$)} & $+0.43$ {\scriptsize ($n{=}8031$)} & $+0.13$ {\scriptsize ($n{=}6365$)} & $+0.35$ {\scriptsize ($n{=}65$)} & $+0.27$ {\scriptsize ($n{=}155$)} \\
ROUGE & $+0.68$ {\scriptsize ($n{=}416$)} & $+0.56$ {\scriptsize ($n{=}8031$)} & $+0.25$ {\scriptsize ($n{=}6365$)} & $+0.61$ {\scriptsize ($n{=}65$)} & $+0.37$ {\scriptsize ($n{=}155$)} \\
METEOR & $+0.61$ {\scriptsize ($n{=}208$)} & $+0.48$ {\scriptsize ($n{=}8031$)} & $+0.28$ {\scriptsize ($n{=}6365$)} & $+0.27$ {\scriptsize ($n{=}65$)} & $+0.36$ {\scriptsize ($n{=}155$)} \\
chrF & --- & --- & $+0.33$ {\scriptsize ($n{=}6365$)} & --- & --- \\
BERTScore & $+0.47$ {\scriptsize ($n{=}208$)} & $+0.39$ {\scriptsize ($n{=}8031$)} & $+0.26$ {\scriptsize ($n{=}6365$)} & --- & --- \\
MoverScore & $+0.59$ {\scriptsize ($n{=}208$)} & $+0.52$ {\scriptsize ($n{=}8024$)} & $+0.12$ {\scriptsize ($n{=}6365$)} & $+0.38$ {\scriptsize ($n{=}16$)} & $+0.61$ {\scriptsize ($n{=}28$)} \\
Semantic sim. & $+0.33$ {\scriptsize ($n{=}208$)} & $+0.19$ {\scriptsize ($n{=}8031$)} & $+0.15$ {\scriptsize ($n{=}6365$)} & $+0.20$ {\scriptsize ($n{=}16$)} & $+0.37$ {\scriptsize ($n{=}29$)} \\
\bottomrule
\end{tabular*}
\end{table*}

\begin{figure*}[p]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{manuscript_files/figure-pdf/fig-metric-correlation-output-1.pdf}}

}

\caption{\label{fig-metric-correlation}Per-generation correlation
between each automatic metric and the LLM-judge raw score on the
Benchathon (left), ZJS (middle), and Doctrinal Principles (right)
corpora. Bars report Pearson r and Spearman \(\rho\); n varies per
metric. Metrics are shown in the fixed canonical order shared with the
per-corpus correlation table in this appendix. Judge on Doctrinal
Principles is the custom 4-dimension rubric.}

\end{figure*}%

\section{Judge--human agreement
statistics}\label{judgehuman-agreement-statistics}

Table~\ref{tbl-agreement} reports the headline judge--human and
human--human agreement numbers; Figure~\ref{fig-rubric-dim} breaks the
same data down by rubric dimension.

\input{assets/tbl_agreement.tex}

\begin{figure*}[p]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{manuscript_files/figure-pdf/fig-rubric-dim-output-1.pdf}}

}

\caption{\label{fig-rubric-dim}Per-rubric-dimension agreement between
the LLM judge and the mean of the blind human reviewers, split by
solution provenance. Left: human-authored solutions (\(n=30\)). Right:
LLM-generated solutions (\(n=15\)). Bars: Pearson r (bottom axis).
Points: MAE in dimension points (top axis). Dimension ordering is shared
across panels (sorted by human-side Pearson). Hatched bars marked
\texttt{n/a} indicate that the judge returned a constant score across
the 15 LLM picks on that dimension, leaving the Pearson statistic
mathematically undefined (judge variance = 0); the MAE is still
well-defined and is plotted.}

\end{figure*}%

\section{System prompts for
generation}\label{system-prompts-for-generation}

\emph{All prompts in this and the following two appendices (Appendices
\ref{instruction-prompts-for-generation} and
\ref{evaluation-prompts-for-the-llm-judge}) were sent to the models
verbatim in German as reproduced below. Each German prompt is followed
by an English translation marked as such; the translations are provided
for reader convenience and were not used in any model interaction.}

\subsection{Exam-style cases
(Klausuren)}\label{exam-style-cases-klausuren}

Du bist ein hochqualifizierter juristischer Bearbeiter für deutsches
Recht. Du bearbeitest juristische Klausuren methodisch sauber, präzise
und strukturiert nach den Standards deutscher juristischer Ausbildung
und Prüfungspraxis.

Du argumentierst streng fallbezogen und orientierst dich an den
Anforderungen universitärer Klausuren sowie des ersten Staatsexamens. Du
löst Aufgaben eigenständig und ohne Meta-Kommentare.

\emph{English translation (reader reference; not sent to any model):}

You are a highly qualified legal practitioner for German law. You work
through legal exam-style cases (\emph{Klausuren}) methodically,
precisely, and in a structured manner, in line with the standards of
German legal education and examination practice.

You argue strictly with reference to the case at hand and orient
yourself to the requirements of university exam-style cases and of the
first state examination (\emph{Erstes Staatsexamen}). You solve tasks
independently and without meta-commentary.

\subsection{Doctrinal Principles
(Grundprinzipien)}\label{doctrinal-principles-grundprinzipien}

Du bist ein hochqualifizierter juristischer Bearbeiter für deutsches
Recht. Du beantwortest juristische Fragen präzise, methodisch sauber und
streng fallbezogen nach den Standards deutscher Rechtswissenschaft.

Deine Antworten sollen knapp, klar und juristisch korrekt sein. Im
Mittelpunkt steht die zutreffende Anwendung rechtlicher Grundprinzipien
auf den konkreten Sachverhalt. Du argumentierst eigenständig und ohne
Meta-Kommentare.

\emph{English translation (reader reference; not sent to any model):}

You are a highly qualified legal practitioner for German law. You answer
legal questions precisely, methodically, and strictly with reference to
the case at hand, in line with the standards of German legal
scholarship.

Your answers should be concise, clear, and legally correct. The focus is
on the accurate application of fundamental legal principles to the
concrete fact pattern. You argue independently and without
meta-commentary.

\section{Instruction prompts for
generation}\label{instruction-prompts-for-generation}

\subsection{Exam-style cases
(Klausuren)}\label{exam-style-cases-klausuren-1}

Bearbeite die folgende juristische Aufgabe wie eine echte deutsche
Jura-Klausur.

\paragraph{\texorpdfstring{\textbf{Ziel der
Bearbeitung}}{Ziel der Bearbeitung}}\label{ziel-der-bearbeitung}

Erstelle eine vollständige juristische Falllösung nach den methodischen
Standards deutscher Rechtswissenschaft. Im Mittelpunkt steht
subsumptionsbasierte Rechtsanwendung.

Die Bearbeitung soll zeigen, dass du:

\begin{itemize}
\tightlist
\item
  die rechtlichen Kernprobleme des Falls erkennst,
\item
  die relevanten Anspruchsgrundlagen bzw. Prüfungsprogramme auswählst,
\item
  die Prüfung methodisch korrekt strukturierst,
\item
  Definitionen und Streitstände präzise einordnest,
\item
  vor allem aber die konkreten Tatsachen des Falls sauber unter die
  rechtlichen Voraussetzungen subsumierst.
\end{itemize}

Die Qualität der juristischen Argumentation ist wichtiger als reine
Vollständigkeit oder Länge.

\paragraph{Stil, Methodik und
Gliederung}\label{stil-methodik-und-gliederung}

Arbeite im Stil einer deutschen juristischen Klausur.

Grundsätzlich ist die Lösung im Gutachtenstil zu verfassen. Das bedeutet
insbesondere:

\begin{itemize}
\tightlist
\item
  Formulierung eines Obersatzes,
\item
  Definition der rechtlichen Voraussetzungen,
\item
  Subsumtion anhand des konkreten Sachverhalts,
\item
  nachvollziehbares Zwischenergebnis.
\end{itemize}

Nur wenn aus Aufgabenstellung, Ausbildungsniveau oder
Bearbeitungskontext erkennbar ist, dass eine Referendarsklausur oder ein
Urteil verlangt wird, ist stattdessen im Urteilsstil zu arbeiten. In
diesem Fall soll die Lösung den typischen Aufbau gerichtlicher
Entscheidungen widerspiegeln, insbesondere eine ergebnisorientierte
Darstellung mit anschließender Begründung.

Die juristische Methodik muss unabhängig vom Stil jederzeit klar
erkennbar bleiben.

Die Lösung ist klausurtypisch und hierarchisch sauber zu gliedern. Nutze
die in der deutschen Juristenausbildung üblichen Gliederungsebenen und
Bezeichnungen.

Typischerweise:

A., B., C. für Hauptabschnitte,

I., II., III. für Unterabschnitte,

1., 2., 3. für weitere Ebenen,

a), b), c) für Unterpunkte,

aa), bb), cc) für vertiefte Untergliederungen.

Jede Gliederungsebene soll inhaltlich sinnvoll, logisch konsistent und
leicht nachvollziehbar sein. Das bedeutet insbesondere:

\begin{itemize}
\tightlist
\item
  strukturiere die Lösung nach Anspruchsgrundlagen, Rechtsbehelfen oder
  Prüfungsprogrammen,
\item
  prüfe Anspruchsvoraussetzungen in methodisch sinnvoller Reihenfolge,
\item
  bilde erkennbare Prüfungsschwerpunkte heraus,
\item
  nutze Zwischenergebnisse zur Strukturierung der weiteren Prüfung,
\item
  vermeide unstrukturierte Textblöcke oder sprunghafte Argumentation.
\end{itemize}

Die Qualität der juristischen Strukturierung ist Teil der
Bearbeitungsleistung.

\paragraph{\texorpdfstring{\textbf{Schwerpunktsetzung}}{Schwerpunktsetzung}}\label{schwerpunktsetzung}

Gewichte die Bearbeitung klausurtypisch.

Das bedeutet:

\begin{itemize}
\tightlist
\item
  konzentriere dich auf die rechtlich schwierigen und problematischen
  Punkte,
\item
  behandle offensichtliche oder unproblematische Voraussetzungen kurz,
\item
  erkenne versteckte Probleme und Schwerpunktsetzungen im Sachverhalt,
\item
  vermeide lange Ausführungen zu irrelevanten Nebenaspekten.
\end{itemize}

\paragraph{Umgang mit Streitständen}\label{umgang-mit-streitstuxe4nden}

Die Darstellung relevanter Streitstände ist in juristischen Klausuren
grundsätzlich erwünscht, insbesondere wenn sie zu den Kernproblemen des
Falls gehören oder methodisch vertiefte Argumentation ermöglichen.

Wenn mehrere vertretbare Ansichten bestehen:

\begin{itemize}
\tightlist
\item
  stelle die wesentlichen Positionen präzise dar,
\item
  arbeite Unterschiede in Argumentation oder dogmatischer Herleitung
  heraus,
\item
  argumentiere methodisch und fallbezogen,
\item
  entscheide dich nachvollziehbar für eine Ansicht,
\item
  arbeite anschließend konsequent mit der gewählten Ansicht weiter.
\end{itemize}

Die Darstellung darf über das absolut unmittelbar Notwendige
hinausgehen, sofern sie klausurtypisch ist und zum Schwerpunkt der
Aufgabe passt. Vermeide jedoch:

\begin{itemize}
\tightlist
\item
  rein auswendig gelernte oder schematische Streitdarstellungen ohne
  Fallbezug,
\item
  extensive Meinungsstreite zu nebensächlichen Problemen,
\item
  reine Namens- oder Schlagwortaufzählungen ohne argumentative
  Einordnung.
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Umgang mit dem
Sachverhalt}}{Umgang mit dem Sachverhalt}}\label{umgang-mit-dem-sachverhalt}

Arbeite streng sachverhaltsbezogen.

\begin{itemize}
\tightlist
\item
  Nutze konkrete Tatsachen aktiv in der Subsumtion.
\item
  Erfinde keine zusätzlichen Tatsachen.
\item
  Unterstelle keine Informationen, die nicht im Sachverhalt enthalten
  sind.
\item
  Ignoriere keine auffälligen Hinweise oder Indizien.
\end{itemize}

Wenn Informationen fehlen, arbeite mit dem vorhandenen Sachverhalt
weiter und kennzeichne verbleibende Unsicherheiten juristisch sauber.

\paragraph{\texorpdfstring{\textbf{Normen und
Zitierweise}}{Normen und Zitierweise}}\label{normen-und-zitierweise}

Nenne die einschlägigen gesetzlichen Grundlagen präzise.

\begin{itemize}
\tightlist
\item
  Zitiere Normen möglichst vollständig.
\item
  Nutze Absätze, Sätze, Nummern oder Buchstaben, wenn relevant.
\item
  Verwende deutsche juristische Terminologie.
\end{itemize}

Beispiele:

\begin{itemize}
\tightlist
\item
  „§ 823 Abs. 1 BGB''
\item
  „Art. 12 Abs. 1 GG''
\item
  „§ 242 StGB''
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Sprachstil}}{Sprachstil}}\label{sprachstil}

\begin{itemize}
\tightlist
\item
  Schreibe sachlich, präzise und juristisch.
\item
  Vermeide Meta-Kommentare.
\item
  Erwähne nicht, dass du ein KI-System bist.
\item
  Gib keine allgemeinen Haftungsausschlüsse.
\item
  Verweise nicht auf externe Beratung.
\item
  Antworte direkt mit der juristischen Lösung.
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Umfang}}{Umfang}}\label{umfang}

Die Lösung soll so ausführlich sein, wie es für eine gute bis sehr gute
juristische Klausurbearbeitung erforderlich ist.

\begin{itemize}
\tightlist
\item
  Wichtige Probleme sollen vertieft behandelt werden.
\item
  Unproblematische Punkte dürfen knapp bleiben.
\item
  Die Lösung soll nicht künstlich verlängert werden.
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Ausgabeformat}}{Ausgabeformat}}\label{ausgabeformat}

\begin{itemize}
\tightlist
\item
  Gib ausschließlich die juristische Lösung aus.
\item
  Nutze sinnvolle Überschriften und Gliederungsebenen.
\item
  Verwende Fließtext.
\item
  Keine Stichpunkte außer wenn methodisch sinnvoll.
\item
  Keine zusätzlichen Erklärungen außerhalb der Falllösung.
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Aufgabe}}{Aufgabe}}\label{aufgabe}

\{\{sachverhalt\}\}

\emph{English translation (reader reference; not sent to any model):}

Work through the following legal task as if it were a genuine German law
exam-style case (\emph{Klausur}).

\paragraph{\texorpdfstring{\textbf{Goal of the
work}}{Goal of the work}}\label{goal-of-the-work}

Produce a complete legal case solution (\emph{Falllösung}) according to
the methodological standards of German legal scholarship. The focus is
on subsumption-based (\emph{subsumtionsbasiert}) application of the law.

The work should demonstrate that you:

\begin{itemize}
\tightlist
\item
  identify the core legal problems of the case,
\item
  select the relevant causes of action or examination programmes,
\item
  structure the analysis methodologically correctly,
\item
  classify definitions and scholarly debates (\emph{Streitstände})
  precisely,
\item
  and, above all, cleanly subsume the concrete facts of the case under
  the legal requirements.
\end{itemize}

The quality of the legal argumentation is more important than mere
completeness or length.

\paragraph{Style, methodology, and
structure}\label{style-methodology-and-structure}

Work in the style of a German legal exam-style case.

As a general rule, the solution is to be written in the assessment style
(\emph{Gutachtenstil}). This means in particular:

\begin{itemize}
\tightlist
\item
  formulation of a major premise (\emph{Obersatz}),
\item
  definition of the legal requirements,
\item
  subsumption on the basis of the concrete fact pattern,
\item
  a comprehensible intermediate result.
\end{itemize}

Only when it is evident from the task, the level of training, or the
work context that a trainee's exam-style case
(\emph{Referendarsklausur}) or a judgement is required should the
judgement style (\emph{Urteilsstil}) be used instead. In that case, the
solution should reflect the typical structure of judicial decisions, in
particular a result-oriented presentation followed by the reasoning.

Regardless of style, the legal methodology must remain clearly
recognizable at all times.

The solution must be structured in a typical exam-style way, with a
clean hierarchy. Use the levels and labels customary in German legal
education.

Typically:

A., B., C. for main sections,

I., II., III. for subsections,

1., 2., 3. for further levels,

a), b), c) for sub-points,

aa), bb), cc) for deeper sub-structures.

Each level of structure should be substantively meaningful, logically
consistent, and easy to follow. This means in particular:

\begin{itemize}
\tightlist
\item
  structure the solution by causes of action, legal remedies, or
  examination programmes,
\item
  examine the requirements of a claim in a methodologically sensible
  order,
\item
  bring out recognizable focal points of the analysis,
\item
  use intermediate results to structure the further analysis,
\item
  avoid unstructured blocks of text or erratic argumentation.
\end{itemize}

The quality of the legal structuring is part of the work being assessed.

\paragraph{\texorpdfstring{\textbf{Setting
priorities}}{Setting priorities}}\label{setting-priorities}

Weight the work in the manner typical of an exam-style case.

This means:

\begin{itemize}
\tightlist
\item
  concentrate on the legally difficult and problematic points,
\item
  treat obvious or unproblematic requirements briefly,
\item
  recognise hidden problems and focal points in the fact pattern,
\item
  avoid lengthy discussion of irrelevant secondary aspects.
\end{itemize}

\paragraph{Handling scholarly debates}\label{handling-scholarly-debates}

The presentation of relevant scholarly debates (\emph{Streitstände}) is
generally desirable in legal exam-style cases, especially when they
concern the core problems of the case or enable methodologically deeper
argumentation.

When several defensible views exist:

\begin{itemize}
\tightlist
\item
  present the essential positions precisely,
\item
  bring out differences in argumentation or doctrinal derivation,
\item
  argue methodologically and with reference to the case,
\item
  decide for one view in a comprehensible way,
\item
  and then work consistently with the chosen view.
\end{itemize}

The presentation may go beyond what is absolutely strictly necessary,
provided it is typical of an exam-style case and fits the focus of the
task. However, avoid:

\begin{itemize}
\tightlist
\item
  purely rote or schematic presentations of legal controversies without
  a connection to the case,
\item
  extensive doctrinal disputes on secondary issues,
\item
  mere name-dropping or buzzword listings without argumentative
  classification.
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Handling the fact
pattern}}{Handling the fact pattern}}\label{handling-the-fact-pattern}

Work strictly with reference to the fact pattern (\emph{Sachverhalt}).

\begin{itemize}
\tightlist
\item
  Use concrete facts actively in the subsumption.
\item
  Do not invent additional facts.
\item
  Do not assume information that is not contained in the fact pattern.
\item
  Do not ignore any conspicuous indications or pieces of evidence.
\end{itemize}

If information is missing, continue working with the fact pattern as
given and mark any remaining uncertainties in a legally clean manner.

\paragraph{\texorpdfstring{\textbf{Norms and citation
style}}{Norms and citation style}}\label{norms-and-citation-style}

Cite the applicable statutory grounds precisely.

\begin{itemize}
\tightlist
\item
  Cite norms as completely as possible.
\item
  Use paragraphs, sentences, numbers, or letters when relevant.
\item
  Use German legal terminology.
\end{itemize}

Examples:

\begin{itemize}
\tightlist
\item
  ``§ 823 Abs. 1 BGB''
\item
  ``Art. 12 Abs. 1 GG''
\item
  ``§ 242 StGB''
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Language and
style}}{Language and style}}\label{language-and-style}

\begin{itemize}
\tightlist
\item
  Write objectively, precisely, and in a legal register.
\item
  Avoid meta-commentary.
\item
  Do not mention that you are an AI system.
\item
  Do not give general disclaimers.
\item
  Do not refer to external advice.
\item
  Respond directly with the legal solution.
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Length}}{Length}}\label{length}

The solution should be as detailed as required for a good to very good
legal exam-style case solution.

\begin{itemize}
\tightlist
\item
  Important problems should be treated in depth.
\item
  Unproblematic points may be kept short.
\item
  The solution should not be artificially extended.
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Output
format}}{Output format}}\label{output-format}

\begin{itemize}
\tightlist
\item
  Output only the legal solution.
\item
  Use meaningful headings and levels of structure.
\item
  Use running prose.
\item
  No bullet points except where methodologically sensible.
\item
  No additional explanations outside the case solution.
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Task}}{Task}}\label{task}

\{\{sachverhalt\}\}

\subsection{Doctrinal Principles
(Grundprinzipien)}\label{doctrinal-principles-grundprinzipien-1}

Bearbeite die folgende juristische Frage nach deutschem Recht.

\paragraph{Ziel}\label{ziel}

Gib eine kurze, präzise und methodisch saubere juristische Antwort auf
die konkrete Fragestellung.

Die Antwort soll:

\begin{itemize}
\tightlist
\item
  die rechtlich relevante Kernfrage erkennen,
\item
  die einschlägigen Normen oder Prinzipien benennen,
\item
  den konkreten Sachverhalt knapp subsumieren,
\item
  und zu einer klaren Ja-/Nein-Entscheidung gelangen.
\end{itemize}

\paragraph{Stil}\label{stil}

Die Antwort soll deutlich kürzer und fokussierter sein als eine
vollständige Klausurlösung.

\begin{itemize}
\tightlist
\item
  Keine umfangreiche Gliederung.
\item
  Keine langen Streitstandsdebatten.
\item
  Keine künstliche Verlängerung.
\item
  Keine allgemeinen Lehrbuchausführungen.
\end{itemize}

Wenn mehrere vertretbare Ansichten bestehen:

\begin{itemize}
\tightlist
\item
  stelle die wesentlichen Unterschiede knapp dar,
\item
  entscheide dich nachvollziehbar,
\item
  und arbeite konsistent mit der gewählten Ansicht weiter.
\end{itemize}

\paragraph{Sachverhaltsbezug}\label{sachverhaltsbezug}

Arbeite streng sachverhaltsbezogen.

\begin{itemize}
\tightlist
\item
  Nutze nur Informationen aus Fall und Fragestellung.
\item
  Erfinde keine zusätzlichen Tatsachen.
\item
  Vermeide abstrakte Standardformulierungen ohne Fallbezug.
\end{itemize}

\paragraph{Ausgabeformat}\label{ausgabeformat-1}

Gib ausschließlich gültiges JSON im folgenden Format aus:

\begin{verbatim}
{
"answer": "Ja" oder "Nein",
"reasoning": "kurze juristische Begründung"
}
\end{verbatim}

\paragraph{Fall}\label{fall}

\{\{fall\}\}

\paragraph{Fragestellung}\label{fragestellung}

\{\{task\}\}

\emph{English translation (reader reference; not sent to any model):}

Work through the following legal question under German law.

\paragraph{Goal}\label{goal}

Give a short, precise, and methodologically clean legal answer to the
concrete question.

The answer should:

\begin{itemize}
\tightlist
\item
  identify the legally relevant core question,
\item
  name the applicable norms or principles,
\item
  briefly subsume the concrete fact pattern,
\item
  and arrive at a clear Ja/Nein decision.
\end{itemize}

\paragraph{Style}\label{style}

The answer should be considerably shorter and more focused than a full
exam-style case solution.

\begin{itemize}
\tightlist
\item
  No extensive structuring.
\item
  No long discussions of scholarly debates.
\item
  No artificial padding.
\item
  No general textbook expositions.
\end{itemize}

When several defensible views exist:

\begin{itemize}
\tightlist
\item
  briefly present the essential differences,
\item
  decide for one view in a comprehensible way,
\item
  and work consistently with the chosen view.
\end{itemize}

\paragraph{Reference to the fact
pattern}\label{reference-to-the-fact-pattern}

Work strictly with reference to the fact pattern.

\begin{itemize}
\tightlist
\item
  Use only information from the case and the question.
\item
  Do not invent additional facts.
\item
  Avoid abstract standard formulations without a connection to the case.
\end{itemize}

\paragraph{Output format}\label{output-format-1}

Output only valid JSON in the following format:

\begin{verbatim}
{
"answer": "Ja" or "Nein",
"reasoning": "short legal justification"
}
\end{verbatim}

\paragraph{Case}\label{case}

\{\{fall\}\}

\paragraph{Question}\label{question}

\{\{task\}\}

\section{Evaluation prompts for the LLM
judge}\label{evaluation-prompts-for-the-llm-judge}

\subsection{Exam-style cases
(Klausuren)}\label{exam-style-cases-klausuren-2}

Du bist ein strenger, aber fairer Korrektor (``LLM Judge'') für
juristische Klausuren deutscher Studierender bis zum 1. Staatsexamen.

Du bewertest ausschließlich auf Basis von: 1. Angabe/Sachverhalt, 2.
Studierendenlösung, 3. Musterlösung.

Nutze keine externen Quellen und erfinde keine Tatsachen.

Grundsätze:

\begin{itemize}
\tightlist
\item
  Musterlösung ist Referenz. Vergib aber vergleichbar Punkte für
  vertretbare Alternativlösungen, wenn sie mit der Angabe vereinbar und
  methodisch sauber begründet sind.
\item
  Folgefehlerprinzip: Einen Fehler nicht doppelt bestrafen. Wenn ein
  früher Fehler spätere Teile beeinflusst, bewerte die spätere
  Argumentation unter der Prämisse des studentischen
  Zwischenergebnisses, soweit methodisch sauber.
\item
  Keine Punkte für bloße Schlagworte ohne Definition/Subsumtion.
\item
  Beziehe dich in der Begründung konkret darauf, was in der
  Studierendenlösung steht und wie es zur Musterlösung passt.
\end{itemize}

Bewertungsschema (insgesamt 100 Punkte):

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Ergebnisrichtigkeit (0--20): \textbf{Vollpunkte (≈18--20):}
  Kernergebnisse stimmen mit Musterlösung überein oder sind vertretbar
  gleichwertig (z.B. anderes, aber methodisch korrekt begründetes
  Ergebnis). \textbf{Mittel (≈10--14):} Haupttendenz stimmt, aber ein
  wesentliches Ergebnis ist falsch oder Rechtsfolgen sind merklich
  verfehlt. \textbf{Niedrig (≈0--8):} Zentrale Ergebnisse
  verfehlt/inkonsistent; Lösung läuft am Fall vorbei.
\item
  Vollständigkeit \& Problemidentifikation (0--10): \textbf{Vollpunkte
  (≈9--10):} Alle wesentlichen Probleme aus Angabe/Musterlösung erkannt;
  keine großen „blinden Flecken``. \textbf{Mittel (≈5--7):} Ein
  wesentliches Problem fehlt oder ein Schwerpunkt wird übersehen; sonst
  ordentlich. \textbf{Niedrig (≈0--4):} Mehrere zentrale Probleme fehlen
  oder es werden viele irrelevante Nebenthemen geprüft („Themenklausur``
  statt Falllösung).
\item
  Rechtsgrundlagen \& Prüfungssystematik (0--10): \textbf{Vollpunkte
  (≈9--10):} Richtige Anspruchsgrundlagen/Prüfungsprogramme, logische
  Reihenfolge, saubere Prüfungsabschnitte. \textbf{Mittel (≈5--7):}
  Kleine Systematikfehler (Reihenfolge, einzelne falsche/unnötige
  Grundlagen), aber Gesamtstruktur trägt. \textbf{Niedrig (≈0--4):}
  Falsche Grundstruktur (z.B. falscher Rechtsbehelf/Anspruch, falscher
  Prüfungsrahmen), sodass die Prüfung methodisch entgleist.
\item
  Rechtskenntnis (Definitionen, Normen, Streitstände) (0--15):
  \textbf{Vollpunkte (≈13--15):} Definitionen korrekt, Normen passend,
  Streitstände nur dort, wo nötig; Streitentscheid begründet.
  \textbf{Mittel (≈8--11):} Einzelne Definitionen/Normen ungenau;
  Streitstände schematisch oder lückenhaft, aber nicht fallentscheidend
  falsch. \textbf{Niedrig (≈0--7):} Häufig falsche Definitionen/Normen
  oder erfundene Anforderungen; Streitstände wirr/fehlerhaft.
\item
  Subsumtion \& Argumentationsqualität (Fallbezug) (0--15):
  \textbf{Vollpunkte (≈13--15):} Konsequenter Tatsachenbezug, saubere
  Subsumtion, nachvollziehbare Argumente, Abwägungen strukturiert.
  \textbf{Mittel (≈8--11):} Teilweise nur abstrakt/„leerformelhaft``,
  aber wesentliche Punkte werden noch fallbezogen gelöst.
  \textbf{Niedrig (≈0--7):} Kaum Subsumtion, überwiegend Definitionen
  ohne Anwendung; Ergebnisse nicht begründet oder widersprüchlich.
\item
  Schwerpunktsetzung \& Problemtiefe (0--10): \textbf{Vollpunkte
  (≈9--10):} Langer Sachverhaltsblock/Indizien → angemessen vertieft;
  einfache Punkte kurz; Schwerpunkt stimmt mit Musterlösung und
  „Signalen`` der Angabe überein. \textbf{Mittel (≈5--7):} Entweder
  Überlänge bei Nebensachen oder Untergewichtung eines Schwerpunkts,
  aber noch erkennbares Klausurbewusstsein. \textbf{Niedrig (≈0--4):}
  Massive Fehlgewichtung: Hauptproblem kaum behandelt, Nebensachen
  dominieren.
\item
  Methodischer Stil: Obersatz → Definition → Subsumtion → Ergebnis
  (0--10): \textbf{Vollpunkte (≈9--10):} Bei allen wichtigen
  Prüfungspunkten klar erkennbar; Zwischenergebnisse werden gezogen;
  auch im Urteilsstil sinngemäß eingehalten. \textbf{Mittel (≈5--7):}
  Grundschema vorhanden, aber häufiger vermischt/ausgelassen;
  Definitionen oder Ergebnisse fehlen gelegentlich. \textbf{Niedrig
  (≈0--4):} Kein prüfungsorientierter Stil; nur Nacherzählung,
  Stichworte, oder reine Ergebnisbehauptungen.
\item
  Gliederung, Gliederungsebenen \& Leseführung (0--5): \textbf{5:}
  Stringente Gliederung, Ebenen sauber, Prüfpunkte auffindbar.
  \textbf{3--4:} Kleinere Inkonsistenzen (Ebenensprünge, Überschriften
  nicht passgenau). \textbf{0--2:} Unstrukturierter Textblock;
  Gliederung irreführend.
\item
  Sprache \& juristische Terminologie (0--3): \textbf{3:} Präzise,
  juristisch sauber, gut verständlich. \textbf{2:} Teilweise
  umständlich/ungenau, aber verständlich. \textbf{0--1:} Häufig
  missverständlich, falsche Begriffe, viele sprachliche Brüche.
\item
  Formalia: Normzitierweise, Sachverhaltsarbeit, Sorgfalt (0--2):
  \textbf{2:} Normen überwiegend korrekt zitiert; Sachverhalt korrekt
  verarbeitet; keine groben Schnitzer. \textbf{1:} Einzelne
  Zitier-/Sorgfaltsfehler, nicht gravierend. \textbf{0:} Häufige grobe
  Fehler (Rollen vertauscht, zentrale Fakten falsch wiedergegeben,
  Normchaos).
\end{enumerate}

Umrechnung Rohpunkte → Notenpunkte (0--18; \textless4 = nicht
bestanden): 0--12→0, 13--25→1, 26--38→2, 39--49→3, 50--53→4, 54--56→5,
57--59→6, 60--63→7, 64--66→8, 67--69→9, 70--73→10, 74--76→11, 77--79→12,
80--83→13, 84--86→14, 87--89→15, 90--93→16, 94--96→17, 97--100→18

Ausgabeformat:

\begin{itemize}
\tightlist
\item
  Gib eine JSON-Ausgabe ohne zusätzlichen Text aus.
\item
  Für jede Dimension: score (0 bis max, ggf. 0.5 Schritte), max, und
  eine Begründung als zusammenhängender Absatz (3--7 Sätze).
\item
  Danach: total\_score (0--100), grade\_points (0--18), passed
  (true/false), kurze Gesamtwürdigung (2--5 Sätze) und 3 konkrete
  Verbesserungshinweise.
\end{itemize}

ANGABE / SACHVERHALT: \{\{\{ANGABE\_TEXT\}\}\}

MUSTERLÖSUNG: \{\{\{MUSTERLOESUNG\_TEXT\}\}\}

STUDIERENDENLÖSUNG: \{\{\{LOESUNG\_TEXT\}\}\}

Aufgabe: Bewerte die Lösung nach dem vorgegebenen 100-Punkte-Schema.
Vergib zu jeder Dimension Punkte und schreibe eine Begründung als
Absatz. Berechne die Summe (0--100) und wandle in Notenpunkte (0--18)
um. Markiere passed=true nur, wenn grade\_points \textgreater= 4.

Gib ausschließlich JSON aus.

\emph{English translation (reader reference; not sent to any model):}

You are a strict but fair grader (``LLM Judge'') for legal exam-style
cases written by German students up to the first state examination
(\emph{Erstes Staatsexamen}).

You evaluate exclusively on the basis of: 1. the task/fact pattern, 2.
the student solution (\emph{Studierendenlösung}), 3. the reference
solution (\emph{Musterlösung}).

Do not use any external sources and do not invent any facts.

Principles:

\begin{itemize}
\tightlist
\item
  The reference solution is the benchmark. However, award comparable
  points for defensible alternative solutions, provided they are
  compatible with the task and methodologically soundly reasoned.
\item
  Follow-on-error principle (\emph{Folgefehlerprinzip}): do not punish
  one error twice. If an early error affects later parts, evaluate the
  later argumentation on the assumption of the student's intermediate
  result, to the extent this is methodologically clean.
\item
  No points for mere buzzwords without definition / subsumption.
\item
  In your justification, refer concretely to what the student solution
  says and how it fits the reference solution.
\end{itemize}

Grading scheme (100 points in total):

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Correctness of result (0--20): \textbf{Full points (≈18--20):} core
  results match the reference solution or are defensibly equivalent
  (e.g.~a different but methodologically correctly reasoned result).
  \textbf{Middle (≈10--14):} the main tendency is right, but one
  essential result is wrong or the legal consequences are noticeably
  off. \textbf{Low (≈0--8):} central results are missed / inconsistent;
  the solution misses the point of the case.
\item
  Completeness and problem identification (0--10): \textbf{Full points
  (≈9--10):} all essential problems from the task / reference solution
  are recognised; no major ``blind spots''. \textbf{Middle (≈5--7):} one
  essential problem is missing or a focal point is overlooked; otherwise
  sound. \textbf{Low (≈0--4):} several central problems are missing, or
  many irrelevant side topics are examined (``topic essay'' instead of
  case solution).
\item
  Legal bases and examination systematics (0--10): \textbf{Full points
  (≈9--10):} correct causes of action / examination programmes, logical
  sequence, clean examination sections. \textbf{Middle (≈5--7):} small
  systematic errors (sequence, individual incorrect / unnecessary
  bases), but the overall structure holds. \textbf{Low (≈0--4):} wrong
  basic structure (e.g.~wrong legal remedy / claim, wrong examination
  framework), so that the analysis methodologically derails.
\item
  Legal knowledge (definitions, norms, scholarly debates) (0--15):
  \textbf{Full points (≈13--15):} definitions are correct, norms are
  apt, scholarly debates appear only where needed; the decision in the
  debate is reasoned. \textbf{Middle (≈8--11):} individual definitions /
  norms are imprecise; scholarly debates are schematic or patchy, but
  not wrong in a case-decisive way. \textbf{Low (≈0--7):} frequently
  wrong definitions / norms or invented requirements; scholarly debates
  are muddled / faulty.
\item
  Subsumption and quality of argumentation (connection to the case)
  (0--15): \textbf{Full points (≈13--15):} consistent reference to
  facts, clean subsumption, comprehensible arguments, structured
  balancing. \textbf{Middle (≈8--11):} in part only abstract /
  ``empty-formula-like'', but essential points are still solved with
  reference to the case. \textbf{Low (≈0--7):} hardly any subsumption,
  predominantly definitions without application; results are unreasoned
  or contradictory.
\item
  Setting priorities and depth of analysis (0--10): \textbf{Full points
  (≈9--10):} long fact-pattern blocks / indications are appropriately
  treated in depth; easy points are kept short; the focus matches the
  reference solution and the ``signals'' of the task. \textbf{Middle
  (≈5--7):} either overlength on minor matters or under-weighting of a
  focal point, but still recognizable exam awareness. \textbf{Low
  (≈0--4):} massive misallocation: the main problem is barely treated,
  secondary matters dominate.
\item
  Methodological style: major premise → definition → subsumption →
  result (0--10): \textbf{Full points (≈9--10):} clearly recognizable at
  all important examination points; intermediate results are drawn; also
  observed in spirit when written in judgement style. \textbf{Middle
  (≈5--7):} the basic scheme is present but is frequently blended or
  omitted; definitions or results are occasionally missing. \textbf{Low
  (≈0--4):} no examination-oriented style; only narration, bullet
  points, or bare assertions of results.
\item
  Structure, structural levels, and reader guidance (0--5): \textbf{5:}
  stringent structure, clean levels, examination points are findable.
  \textbf{3--4:} small inconsistencies (level jumps, headings not
  precisely fitting). \textbf{0--2:} unstructured block of text;
  structure is misleading.
\item
  Language and legal terminology (0--3): \textbf{3:} precise, legally
  clean, easily understandable. \textbf{2:} partly clumsy / imprecise,
  but understandable. \textbf{0--1:} frequently misleading, wrong terms,
  many linguistic breaks.
\item
  Formalia: norm citation style, work with the fact pattern, care
  (0--2): \textbf{2:} norms cited predominantly correctly; fact pattern
  processed correctly; no gross blunders. \textbf{1:} isolated citation
  / care errors, not serious. \textbf{0:} frequent gross errors (roles
  swapped, central facts misreported, norm chaos).
\end{enumerate}

Conversion of raw points → grade points (0--18; \textless4 = fail):
0--12→0, 13--25→1, 26--38→2, 39--49→3, 50--53→4, 54--56→5, 57--59→6,
60--63→7, 64--66→8, 67--69→9, 70--73→10, 74--76→11, 77--79→12,
80--83→13, 84--86→14, 87--89→15, 90--93→16, 94--96→17, 97--100→18

Output format:

\begin{itemize}
\tightlist
\item
  Output a JSON response without any additional text.
\item
  For each dimension: score (0 to max, in 0.5 steps if needed), max, and
  a justification as a coherent paragraph (3--7 sentences).
\item
  Then: total\_score (0--100), grade\_points (0--18), passed
  (true/false), a short overall assessment (2--5 sentences), and 3
  concrete suggestions for improvement.
\end{itemize}

TASK / FACT PATTERN: \{\{\{ANGABE\_TEXT\}\}\}

REFERENCE SOLUTION: \{\{\{MUSTERLOESUNG\_TEXT\}\}\}

STUDENT SOLUTION: \{\{\{LOESUNG\_TEXT\}\}\}

Task: Evaluate the solution according to the prescribed 100-point
scheme. Award points for each dimension and write a justification as a
paragraph. Calculate the sum (0--100) and convert it into grade points
(0--18). Set passed=true only if grade\_points \textgreater= 4.

Output only JSON.

\subsection{Doctrinal Principles
(Grundprinzipien)}\label{doctrinal-principles-grundprinzipien-2}

Du bist ein strenger, aber fairer juristischer Korrektor für kurze
juristische Begründungsfragen nach deutschem Recht.

Du bewertest ausschließlich auf Basis von:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Fall
\item
  Fragestellung
\item
  Referenzlösung
\item
  Zu bewertende Antwort
\end{enumerate}

Nutze keine externen Quellen und erfinde keine Tatsachen.

\paragraph{Bewertungsgrundsätze}\label{bewertungsgrundsuxe4tze}

\begin{itemize}
\tightlist
\item
  Die Referenzlösung ist Orientierung, nicht die einzig mögliche
  vertretbare Lösung.
\item
  Vergib volle oder nahezu volle Punkte auch für methodisch vertretbare
  Alternativbegründungen.
\item
  Entscheidend ist die juristische Richtigkeit und Qualität der
  Begründung, nicht die sprachliche Ähnlichkeit zur Referenz.
\item
  Keine Punkte für bloße Schlagworte ohne nachvollziehbare Begründung.
\item
  Eine falsche Ja/Nein-Entscheidung begrenzt die Maximalpunktzahl
  erheblich, selbst wenn Teile der Begründung juristisch plausibel sind.
\end{itemize}

\paragraph{Bewertungsschema (100
Punkte)}\label{bewertungsschema-100-punkte}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Ergebnisrichtigkeit (0--40)
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Ist die Ja/Nein-Entscheidung juristisch zutreffend oder vertretbar?
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Rechtskenntnis und Normbezug (0--25)
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Werden einschlägige Normen, Definitionen oder Prinzipien korrekt
  erkannt und verwendet?
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Subsumtion und Fallbezug (0--25)
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Wird der konkrete Sachverhalt nachvollziehbar unter die rechtlichen
  Voraussetzungen subsumiert?
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Klarheit und Präzision (0--10)
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Ist die Antwort präzise, verständlich und methodisch sauber
  formuliert?
\end{itemize}

\paragraph{Ausgabeformat}\label{ausgabeformat-2}

Gib ausschließlich gültiges JSON aus:

\begin{verbatim}
{
"scores": {
"result_correctness": {
"score": ...,
"max": 40,
"reason": "..."
},
"legal_knowledge": {
"score": ...,
"max": 25,
"reason": "..."
},
"subsumption": {
"score": ...,
"max": 25,
"reason": "..."
},
"clarity": {
"score": ...,
"max": 10,
"reason": "..."
}
},
"total_score": ...,
"overall_assessment": "..."
}
\end{verbatim}

\paragraph{Fall}\label{fall-1}

\{\{fall\}\}

\paragraph{Fragestellung}\label{fragestellung-1}

\{\{task\}\}

\paragraph{Referenzlösung}\label{referenzluxf6sung}

Antwort: \{\{binary\_solution\}\}

Begründung: \{\{reasoning\}\}

\paragraph{Zu bewertende Antwort}\label{zu-bewertende-antwort}

\{\{answer\}\}

\emph{English translation (reader reference; not sent to any model):}

You are a strict but fair legal grader for short legal reasoning
questions under German law.

You evaluate exclusively on the basis of:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  the case,
\item
  the question,
\item
  the reference solution,
\item
  the answer to be evaluated.
\end{enumerate}

Do not use any external sources and do not invent any facts.

\paragraph{Grading principles}\label{grading-principles}

\begin{itemize}
\tightlist
\item
  The reference solution is a guide, not the only defensible solution.
\item
  Award full or near-full points also for methodologically defensible
  alternative justifications.
\item
  What matters is the legal correctness and quality of the reasoning,
  not linguistic similarity to the reference.
\item
  No points for mere buzzwords without a comprehensible justification.
\item
  A wrong Ja/Nein decision substantially limits the maximum score, even
  if parts of the reasoning are legally plausible.
\end{itemize}

\paragraph{Grading scheme (100 points)}\label{grading-scheme-100-points}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Correctness of result (0--40)
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Is the Ja/Nein decision legally correct or defensible?
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Legal knowledge and reference to norms (0--25)
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Are the applicable norms, definitions, or principles correctly
  identified and used?
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Subsumption and reference to the case (0--25)
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Is the concrete fact pattern subsumed under the legal requirements in
  a comprehensible way?
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Clarity and precision (0--10)
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Is the answer precisely, understandably, and methodologically cleanly
  formulated?
\end{itemize}

\paragraph{Output format}\label{output-format-2}

Output only valid JSON:

\begin{verbatim}
{
"scores": {
"result_correctness": {
"score": ...,
"max": 40,
"reason": "..."
},
"legal_knowledge": {
"score": ...,
"max": 25,
"reason": "..."
},
"subsumption": {
"score": ...,
"max": 25,
"reason": "..."
},
"clarity": {
"score": ...,
"max": 10,
"reason": "..."
}
},
"total_score": ...,
"overall_assessment": "..."
}
\end{verbatim}

\paragraph{Case}\label{case-1}

\{\{fall\}\}

\paragraph{Question}\label{question-1}

\{\{task\}\}

\paragraph{Reference solution}\label{reference-solution}

Answer: \{\{binary\_solution\}\}

Reasoning: \{\{reasoning\}\}

\paragraph{Answer to be evaluated}\label{answer-to-be-evaluated}

\{\{answer\}\}

\section{LLM-judge configuration}\label{llm-judge-configuration}

The primary judge GPT-5.4-mini is the one used for every reported
leaderboard score and for the RQ5 within-judge stochasticity analysis
(k=3 repeats per generation, in flight as of 2026-06-01). The five
secondary judges Opus-4.7, Gemini-3.1-Pro, DeepSeek-V4-Pro,
Qwen3.5-397B-A17B, and Sonnet-4.6 evaluate every Benchathon cell once
for the RQ5 between-judge bias analysis. The full model ids are shown in
the \emph{Model} column below; see Table~\ref{tbl-system-overview}
(Appendix~\ref{evaluated-systems-catalogue}) for the canonical
alias-to-id mapping.

\input{assets/tbl_judge_config.tex}

The full judge prompts are reproduced in Appendix
\ref{evaluation-prompts-for-the-llm-judge}: the exam-case rubric and the
Doctrinal Principles rubric. All six judges receive the same prompt and
the same input ordering (task, reference solution, solution to be
evaluated); only the underlying model changes.

\section{Judge calibration - supplementary
detail}\label{sec-judge-calibration-supplementary-detail}

This appendix collects the supplementary numerical detail behind the RQ5
per-judge calibration analysis: the six-judge calibration table
referenced from Figure~\ref{fig-judge-calibration}, the within-judge
per-pass breakdown of the primary GPT-5.4-mini judge in
Table~\ref{tbl-judge-calibration-detail}, the per-annotator alt-test
p-values, the per-task per-judge deviation matrix, and a sanity check on
the intersection of picks where the Config-B cross-validation judges
scored.

\paragraph{Per-judge calibration.} Table~\ref{tbl-judge-calibration}
reports the per-judge calibration statistics behind
Figure~\ref{fig-judge-calibration}, with both the direct judge-vs-pool
offset \(\bar{\Delta}_{\text{dir}}=\overline{\text{judge}-\text{full}}\)
(the number to quote when prose says ``the judge sits \(X\) raw points
above the pool'\,') and the Calderon pool-substitution shift
\(\bar{\Delta}_{\text{sub}}=\overline{\text{sub}-\text{full}}\), which
is attenuated by \(1/k\) at \(k=3\) raters. Both come with a paired
\(t\)-test; Shapiro--Wilk fails to reject normality on the
paired-difference series in every cell, so the parametric test applies.

\input{assets/tbl_judge_calibration.tex}

\afterpage{%
\begin{figure*}[t!]
\centering
\includegraphics[width=\textwidth]{assets/pool_normality_per_judge.png}
\caption{Pool-substitution shift $\bar{\Delta}_{\text{sub}} = \bar{\text{sub}} - \bar{\text{full}}$ per judge $\times$ corpus, across the six judges that score the Benchathon validation subset. For each pick, $\text{full}$ is the mean of three blind reviewers and $\text{sub}$ is the mean of two blind reviewers plus the LLM judge; by construction $\bar{\Delta}_{\text{sub}}\approx\bar{\Delta}_{\text{dir}}/3$ where $\bar{\Delta}_{\text{dir}}=\overline{\text{judge}-\text{full}}$ is the direct judge-vs-pool offset reported in Table~\ref{tbl-judge-calibration}. Top row: human-authored picks ($n=30$ for every judge except Opus, where $n=28$ because two evaluations failed the safety filter). Bottom row: LLM-generated picks ($n=15$). The primary GPT-5.4-mini and Opus-4.7 sit essentially on the blind-reviewer pool mean ($p>0.3$ on both, not significantly different); Sonnet-4.6 and DeepSeek-V4-Pro are close on human-content picks and drift mildly lenient on LLM picks; Gemini-3.1-Pro and Qwen3.5-397B-A17B are systematically lenient ($p<0.01$ on both). All paired $\bar{\Delta}_{\text{sub}}$ distributions pass Shapiro--Wilk normality ($p>0.05$); the reported $t$-test is therefore the appropriate inferential test (see Table~\ref{tbl-judge-calibration}).}
\label{fig-judge-calibration}
\end{figure*}%
}

\paragraph{Per-pass detail.} Table~\ref{tbl-judge-calibration-detail}
reports the same per-judge calibration statistics as
Table~\ref{tbl-judge-calibration} but with the three Config-A
GPT-5.4-mini intra-judge passes broken out individually alongside the
baseline single-pass, giving a \(k=4\) within-judge stochasticity check
on the primary judge. The four per-pass offsets cluster with a stdev of
\(1.5\) raw points on human-content picks and \(1.7\) on LLM-content
picks - small relative to the \(+7\) to \(+18\) cross-judge calibration
gradient and the \(\approx\),24-raw-point inter-rater spread of the
blind reviewers, but not strictly deterministic.

\input{assets/tbl_judge_calibration_detail.tex}

\paragraph{Per-annotator alt-test detail.}
Tables~\ref{tbl-calderon-per-annotator-human} and
\ref{tbl-calderon-per-annotator-llm} report the full Calderon blind-pool
alt-test by judge for the human-authored and LLM-generated picks
respectively. Each block's header states the winning rate \(\omega\)
that block accumulates, and the rows below show the five blind
reviewers' per-annotator \(n_j\), \(\rho^f_j\), \(\rho^h_j\),
\(\bar{d}_j\), one-sided \(p\)-value (Wilcoxon signed-rank throughout,
since every \(n_j<30\)), and whether the Benjamini-Yekutieli FDR
procedure at \(q=0.05\) across \(m=5\) rejected the null. Only
annotators flagged \(\star\) contribute to \(\omega\).

\input{assets/tbl_calderon_per_annotator_human.tex}

\input{assets/tbl_calderon_per_annotator_llm.tex}

\paragraph{Intersection sanity check.} Opus-4.7's Benchathon coverage is
\(n=28\) on the human-pick subset rather than \(n=30\) because Opus-4.7
did not produce a parseable score on two picks (likely safety filter or
output-shape failure). Restricting the alt-test to the intersection of
picks every judge scored (\(n=28\)) preserves the per-judge ordering and
the two-judge headline (GPT-5.4-mini and Opus-4.7 still clear
\(\omega\geq 0.5\)), with Sonnet-4.6 and Gemini-3.1-Pro's ``near pass''
at \(\omega=0.40\) on the full \(n=30\) marginally sample-dependent on
the two picks Opus-4.7 missed; we report the full-\(n\) ω in the main
table and treat the intersection as a robustness anchor only.

\subsection{Creator-anchored bias signature and corrected-alt-test
sensitivity}\label{sec-creator-anchored-calibration}

The main-text alt-test ranks the judges by their per-solution offset
against the blind-reviewer pool: GPT-5.4-mini and Opus-4.7 sit close to
the pool and clear the substitution bar, while the lenient judges fail.
This subsection asks a complementary question: does an
\emph{independent} expert anchor reproduce the same offset ranking, or
is the pool-anchored signature an artefact of the specific blind
reviewers we drew? We use the un-blind creator grade as the independent
anchor, since creators (i) hold privileged knowledge of the intended
solution, (ii) are the most legally expert graders on the roster, and
(iii) are excluded from the IRR pool by design and so do not contaminate
the blind-pool alt-test.

\paragraph{Method.} For every (judge, pick) we estimate a leave-one-out
per-judge correction against the creator grade in two tiers reported
side-by-side: a single-parameter \emph{scalar} shift
\(y' = y - \overline{(y_{\text{judge}} - y_{\text{creator}})}\) and a
two-parameter \emph{affine} fit
\(y' = \hat{a} + \hat{b}\,y_{\text{judge}}\) via OLS of creator on
judge. We then re-run the blind-pool alt-test pipeline byte-identically
with calibrated scores substituted, so the only change relative to the
headline Tables~\ref{tbl-calderon-per-annotator-human} and
\ref{tbl-calderon-per-annotator-llm} is the per-pick judge value. Two
leak-clean variants are reported: \textbf{grader-leave-one-out (GLOO)},
in which a tested annotator's creator picks are additionally excluded
from the calibration fit (graders 01 and 04 wear both creator and
blind-reviewer hats across the roster, and a naive LOO would style-train
the judge on the very annotator the alt-test then asks it to replace),
and \textbf{pure-creator}, restricting the anchor to picks whose creator
is grader\_03 or grader\_06 --- the two graders who never appear in the
blind pool --- which is structurally leak-free at the cost of a smaller
anchor (\(n \approx 30\) vs.~\(n \approx 45\)). Calibration is fit
pooled across human + LLM picks; a pool-specific refit is reported as
sensitivity. A stacked bootstrap (resample anchor \emph{and} test set,
refit, re-run alt-test, 500 reps) propagates both calibration and
test-set variance into a 95\% percentile CI on \(\omega\).

\paragraph{Bias-signature finding.} Per-judge LOO scalar coefficients
against the creator under GLOO are tightly clustered for GPT-5.4-mini
(\(\hat{a}_{\text{scalar}} \approx -0.3\)) and Opus-4.7
(\(\hat{a}_{\text{scalar}} \approx +0.5\)) --- both essentially
perfectly calibrated to the strongest grader on the roster --- while
Sonnet-4.6 sits at \(\approx -3.5\), DeepSeek-V4-Pro at \(\approx -4\),
Gemini-3.1-Pro at \(\approx -11\), and Qwen3.5-397B-A17B at
\(\approx -12\) (the negative sign means the judge is lenient relative
to the creator --- equivalently the judge mean sits \(3.5\) to \(12\)
raw points above the creator mean). The affine slope \(\hat{b}\) is
sub-unity for every judge (\(\hat{b} \in [0.77, 0.93]\)), so the judges
also use a slightly compressed range relative to the creator. The
pool-anchored ranking from Table~\ref{tbl-judge-calibration} and the
creator-anchored ranking agree on the strictness order from two
structurally independent reference signals --- the strongest evidence
that the gradient is a property of the judges, not of either grading
subgroup. Per-annotator \((\hat{a},\hat{b})\) spreads across the five
blind reviewers under GLOO are small (\(\hat{a}_{\text{scalar}}\) spread
\(\leq 1.4\) raw points, \(\hat{b}_{\text{affine}}\) spread
\(\leq 0.14\)), confirming the GLOO fit is internally stable.

\paragraph{Corrected-$\omega$ finding.} Under leak-clean GLOO
calibration, the point \(\omega\) lifts for some judges
(e.g.~Qwen3.5-397B-A17B scalar from \(0.00\) to \(0.60\) on human picks;
Sonnet-4.6 scalar to \(0.80\)) but not uniformly --- affine correction
destabilises Opus-4.7's point estimate (from \(0.60\) raw to \(0.00\)
affine), reflecting that a near-identity transform on an
already-calibrated judge can still flip per-instance verdicts at the
\(m=5\) resolution. More importantly, \textbf{no stacked-bootstrap lower
bound clears \(\omega=0.5\) for any judge \(\times\) pool \(\times\)
tier --- including the two judges that already pass at raw scores.} At
\(m=5\) blind reviewers and \(n=30\) picks the alt-test's discrete
\(\omega\) quantum is \(0.20\), so its bootstrap distribution under
resampling spans most of \([0,1]\) for any cell. The strongest signal in
the matrix is GPT-5.4-mini's raw-score stacked-bootstrap lower bound of
\(0.20\), which is what motivates the main-text claim; corrected
\(\omega\) does not improve on it. We therefore treat creator-anchored
calibration as quantifying the per-judge bias \emph{signature} and
explaining the inter-judge alt-test gradient, not as a
calibration-recovery argument.

\paragraph{Pure-creator vs.\ GLOO sensitivity.} The two leak-clean
anchor strategies disagree on point \(\omega\): pure-creator yields more
PASSes at the point estimate (e.g.~GPT-5.4-mini scalar \(\omega=1.00\),
Gemini-3.1-Pro scalar \(\omega=1.00\), DeepSeek-V4-Pro affine
\(\omega=1.00\)) because graders 03 and 06's grading style sits closer
to the average blind reviewer than graders 01 and 04's --- i.e., the
\emph{choice} of expert anchor materially affects the corrected verdict.
Treat the GLOO result as the methodologically conservative reading,
since it uses a strictly larger and more diverse anchor and only
excludes information where strictly necessary for cleanness.

\paragraph{LLM-pick robustness.} Across every calibration tier, anchor
strategy, and \(\varepsilon \in \{0.15, 0.20\}\) examined here, LLM-pick
\(\omega\) stays at \(\{0.00, 0.20\}\) for every judge, and no upper
bootstrap bound clears \(0.55\). The LLM-pick failure is therefore
residual disagreement about what makes a good LLM-generated solution,
not a calibration artefact --- a finding that constrains the Limitations
discussion of judge-human divergence on AI-styled writing rather than
rescuing it.

\section{Responsible NLP Research
Checklist}\label{responsible-nlp-research-checklist}

\subsection{A. For every submission}\label{a.-for-every-submission}

\textbf{A1. Did you describe the limitations of your work?} Yes - §
Limitations enumerates ten distinct limitations: black-box system
evaluation, the co-developed rubric/judge pair, modest Benchathon
participant pool, judge-model bias, RQ5 method caveats,
German-doctrinal-only rubric scope, ZJS pretraining-contamination risk,
descriptive-only sub-cell statistics, Doctrinal-Principles rubric
divergence, and the Google-Flash model drift across corpora.

\textbf{A2. Did you discuss any potential risks of your work?} Yes - §
Ethical considerations covers three risk classes: re-identification of
Benchathon participants (mitigated by anonymisation), copyright on ZJS
material (mitigated by IP-clearance roster, with placeholder URLs for
non-cleared cases), and benchmark gaming or optimisation pressure
(mitigated by releasing the rubric and judge prompts alongside the data
and by reporting per-dimension breakdowns rather than only a headline
score).

\textbf{A3. Do the abstract and introduction summarize the paper's main
claims?} Yes - § Abstract and § Introduction summarise the three
contributions and five research questions; the contributions paragraph
in § Introduction explicitly enumerates them.

\textbf{A4. Have you used AI writing assistants when working on this
paper?} Yes - see § AI usage. Anthropic Claude Opus 4.7 was used for
coding tasks (analysis scripts, table generation, LaTeX assistance);
OpenAI GPT-5.5 Pro was used for wording and LaTeX assistance. No AI
generation of figures, results, or scientific claims.

\subsection{B. Did you use or create scientific
artifacts?}\label{b.-did-you-use-or-create-scientific-artifacts}

\textbf{B1. Did you cite the creators of artifacts you used?} Yes - all
12 evaluated LLM systems are catalogued in
Table~\ref{tbl-system-overview} (Appendix C) with provider, exact model
id, and access date. Related prior benchmarks are cited in § Related
work (GerLayQA, GerLeRB, LegalBench, LexEval, LawBench, LEXam,
GreekBarBench, KOBLEX, NitiBench, PLawBench, LaborBench, CLAUSE,
LegalBench-RAG, Legal RAG Bench). Evaluation metrics are cited at first
use (BLEU, ROUGE, METEOR, BERTScore, MoverScore, ICC, Cohen's
\(\kappa\), Calderon alternative-annotator).

\textbf{B2. Did you discuss the license or terms for use and/or
distribution of any artifacts?} Yes - § Ethical considerations declares
CC BY 4.0 for the BenGER dataset itself; ZJS items are reproduced under
explicit IP-clearance from the original authors (cleared cases bundled;
non-cleared cases linked to the ZJS search interface). The BenGER
platform code is Apache 2.0, separate from the dataset licence.

\textbf{B3. Did you discuss intended use of artifacts?} Yes - § Ethical
considerations states explicitly that the LLM-as-a-Judge methodology is
intended for research-scale evaluation of legal-reasoning systems and is
\textbf{not} validated for use as a graded assessment instrument in
legal education or for deployment in legal practice.

\textbf{B4. Did you discuss steps taken to check whether the data
contains PII or offensive content?} Yes - § Ethical considerations and §
Limitations: Benchathon participants consented to use of their
submissions; all participant identifiers are replaced with pseudonyms;
human-grader identifiers are replaced with stable codes
(\texttt{grader\_01..grader\_07}); ZJS author bylines are public
information from the published journal. No explicit offensive-content
audit is reported because the corpus is doctrinal legal exam material
rather than user-generated text - the offensive-content failure mode is
not plausible at meaningful scale for this domain.

\textbf{B5. Did you provide documentation of the artifacts?} Yes - the
released dataset (Hugging Face + Zenodo) ships with a dataset card, a
per-subset schema description, the IP-clearance roster, and the full
analysis pipeline that reproduces every figure and table in this paper.

\textbf{B6. Did you report relevant statistics about the dataset?} Yes -
§ Dataset reports per-corpus counts (\texttt{n\_zjs},
\texttt{n\_benchathon}, \texttt{n\_qa}), Benchathon human-solution
counts (traditional vs.~human--AI co-creation), and difficulty/bereich
stratification. Appendix E reports Benchathon participant composition.
The dataset is intended for evaluation only and explicitly has no
train/test/dev split (§ Dataset).

\subsection{C. Did you run computational
experiments?}\label{c.-did-you-run-computational-experiments}

\textbf{C1. Did you report the number of parameters, total computational
budget, and infrastructure?} Partial - Appendix C lists exact model ids
for the 12 LLM systems. Parameter counts are public for the open-weight
half; the closed-API providers do not disclose parameter counts.
Appendix B reports per-system mean cost (USD), mean wall-clock response
time, and mean output length, which is the appropriate compute-budget
surrogate for hosted-API evaluation. Infrastructure: generation and
evaluation were run via the BenGER platform \citep{nagl2026benger},
deployed on a single Kubernetes node.

\textbf{C2. Did you discuss the experimental setup, including
hyperparameter search and best-found hyperparameter values?} Yes - §
Experimental setup plus Appendix I (system prompts), Appendix J
(instruction prompts), Appendix K (judge prompts), and Appendix L
(LLM-judge configuration: temperature, max-output-tokens, repetition
count, seed handling). No hyperparameter search was performed; the goal
is to evaluate hosted systems in their as-shipped configuration.

\textbf{C3. Did you report descriptive statistics about your results?}
Yes - every leaderboard cell in Table~\ref{tbl-main-leaderboard} and
Appendix A is reported as mean \(\pm\) half-width of a 95\% confidence
interval (Benchathon: bootstrap with \(B=2000\) resamples, seed 42; ZJS
/ Doctrinal Principles: analytic \(1.96 \cdot \sigma/\sqrt{n}\) via
Welford). Inter-rater statistics include Pearson \(r\), Spearman
\(\rho\), MAE, Cohen's \(\kappa\), ICC(2,1), ICC(2,k), and the Calderon
alternative-annotator coefficient.

\textbf{C4. If you used existing packages, did you report
implementation, version, etc.?} Yes - Appendix L lists judge model ids,
dates, temperature, max-output-tokens, and repetition counts; the
released analysis pipeline pins its Python dependency tree via
\texttt{pyproject.toml} and \texttt{uv.lock}.

\subsection{D. Did you use human annotators or research with human
participants?}\label{d.-did-you-use-human-annotators-or-research-with-human-participants}

\textbf{D1. Did you report the full text of instructions given to
participants?} Yes - Appendix F (full Benchathon human-evaluation
assignment procedure) gives the reviewer-assignment design and the
rubric reviewers saw; the rubric is identical to the one used by the LLM
judge and is reproduced in Appendix K.

\textbf{D2. Did you report information about how you recruited
participants and paid them?} Yes - Appendix E reports participant
composition (law students at various stages, \emph{Referendare}, recent
graduates, a small layperson cohort). Participants received in-kind
compensation in the form of structured exam-style case training and
expert feedback on their submitted solutions - a service for which law
students in Germany typically pay through commercial \emph{Repetitor}
courses. No monetary compensation was provided.

\textbf{D3. Did you discuss whether and how consent was obtained?} Yes -
§ Ethical considerations: participants consented to the use of their
written solutions and self-reported expertise data for research purposes
under the same consent regime that governed the Benchathon event.

\textbf{D4. Was the data collection protocol approved by an ethics
review board?} Yes - the Benchathon study design for the human and
human--AI co-creation baselines was approved by the Technical University
of Munich (TUM) ethics committee, as referenced in § Ethical
considerations.

\textbf{D5. Did you report basic demographic and geographic
characteristics of the annotator population?} Yes - Appendix E
(Benchathon participant composition) reports expertise level
(law-student stage / \emph{Referendar} / graduate / layperson),
legal-area self-assessment, and German-proficiency self-report.
Geographic spread is implicit in the affiliations of the seven human
graders: TUM, LMU Munich, University of Konstanz, and University of
Saarbrücken.

\subsection{E. Did you use AI assistants in your research, coding, or
writing?}\label{e.-did-you-use-ai-assistants-in-your-research-coding-or-writing}

\textbf{E1. Did you discuss whether AI assistants were used for research
ideation?} Yes - AI assistants (Anthropic Claude Opus 4.7, OpenAI
GPT-5.5 Pro) were used as a sounding board for research-question
phrasing and rubric drafting. All final research questions, rubric
dimensions, and experimental-design choices were authored by the human
research team; the AI contributions are bounded to brainstorming and
refinement of wording.

\textbf{E2. Did you discuss whether AI assistants were used for writing
assistance?} Yes - § AI usage declares OpenAI GPT-5.5 Pro for wording
and LaTeX assistance.

\textbf{E3. Did you discuss whether AI assistants were used for coding
or data analysis?} Yes - § AI usage declares Anthropic Claude Opus 4.7
for coding tasks.

% Bibliography is emitted from inside the body (before \appendix) via a raw
% LaTeX block in manuscript.qmd, so the references list appears before the
% appendix per ACL style. Do not re-emit it here.

\end{document}
